(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var u3=function(a){a.ea("cardstatechange",a.Bh()&&a.rk()?1:0)},v3=function(a,b){var c=g.La(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},DPa=function(a){var b=g.sm(a);
a=g.ym(a);return new g.fm(b.x,b.y,a.width,a.height)},EPa=function(a){return Math.pow(a,3)},FPa=function(a){return 3*a*a-2*a*a*a},y3=function(a){a=g.Pa(a);
delete w3[a];g.He(w3)&&x3&&x3.stop()},HPa=function(){x3||(x3=new g.I(function(){GPa()},20));
var a=x3;a.isActive()||a.start()},GPa=function(){var a=g.Ta();
g.se(w3,function(b){IPa(b,a)});
g.He(w3)||HPa()},z3=function(a,b,c,d){g.zr.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.S=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.K=0;this.D=null},IPa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;JPa(a,a.progress);1==a.progress?(a.i=0,y3(a),a.onFinish(),a.Dw()):a.Dc()&&a.jC()},JPa=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.S[c]-a.u[c])*b+a.u[c]},KPa=function(a,b){g.ke.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.i},A3=function(a,b,c,d,e){z3.call(this,b,c,d,e);
this.element=a},B3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
A3.call(this,a,b,c,d,e)},C3=function(a){g.E.call(this);
this.u=a||window;this.i=[]},D3=function(a){return a.baseUrl||null},E3=function(a,b){return g.ep(g.Qm(a,b,void 0),function(c){return!!c})},LPa=function(a,b,c){function d(Y){var Aa,Qa,Ra,sb=Y.hovercardButton;
if(!sb)return null;sb=sb.subscribeButtonRenderer;if(!sb)return null;var Qb=f(sb.unsubscribedButtonText),mc=f(sb.subscribedButtonText);if(sb.subscribed){var Oa=f(sb.subscriberCountWithUnsubscribeText);var cc=f(sb.subscriberCountText)}else Oa=f(sb.subscriberCountText),cc=f(sb.subscriberCountWithSubscribeText);var Kb=null;return Y.signinEndpoint&&(Kb=v3(Y,"signinEndpoint","webNavigationEndpointData","url"),Kb||(Kb=null===(Ra=null===(Qa=null===(Aa=sb.signInEndpoint)||void 0===Aa?void 0:Aa.commandMetadata)||
void 0===Qa?void 0:Qa.webCommandMetadata)||void 0===Ra?void 0:Ra.url),!Kb)?null:Qb&&(mc||Kb)?{subscribed:sb.subscribed,subscribeText:Qb,subscribeCount:Oa,unsubscribeText:mc,unsubscribeCount:cc,enabled:sb.enabled,signinUrl:Kb,classic:Y.useClassicSubscribeButton}:null}
function e(Y){if(Y){var Aa=[],Qa=Y.videoId;Qa&&Aa.push("v="+Qa);(Qa=Y.playlistId)&&Aa.push("list="+Qa);(Y=Y.startTimeSeconds)&&Aa.push("t="+Y);return"/watch?"+Aa.join("&")}}
function f(Y){if(!Y)return null;var Aa=Y.simpleText;return Aa?Aa:Y.runs?g.Qm(Y.runs,function(Qa){return Qa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,q=null,t=null,u=null,x=!1,y=null,z=null,C=null,G=null,F=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,q=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=v3(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):z=f(b.subscribersText)}else"WEBSITE"===
h?((C=v3(l,"urlEndpoint","url"))&&(m=C),n=!0,p="new",C=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(F=f(b.additionalFeesText)),(n=v3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=v3(b,"title","accessibility","accessibilityData","label");var J=b.endpoint?b.endpoint.clickTrackingParams:null,U="";if(b.metadata){var K=f(b.metadata);K&&(U=K)}return{id:"element-"+c,type:h,title:f(b.title),metadata:U,callToAction:f(b.callToAction),SJ:b.image,
iconUrl:C,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:q,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:z,isSubscribe:x,targetUrl:m||null,ES:n,sessionData:J?{itct:J}:null,lX:p,Mu:a?a:null,IS:b.isPlaceholder,impressionUrls:E3(b.impressionUrls||[],D3),wS:E3(b.hovercardShowUrls||[],D3),clickUrls:E3(l.loggingUrls||[],D3),visualElement:g.ey(b.trackingParams),
productPrice:G,additionalFeesText:F}},F3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:E3(a.impressionUrls||[],D3),elements:E3(a.elements||[],function(d,e){return LPa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.ey(a.trackingParams));return c},G3=function(a){g.PM.call(this,a);
this.B=this.endscreen=null;this.i={};this.D={};this.C=this.u=null;this.K=[];this.X=!0;this.I=0;a=a.V();this.S=g.JE(a)||g.NE(a);this.events=new g.aD(this);g.H(this,this.events);this.events.T(this.player,g.Sz("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.Tz("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.xb);this.events.T(window,"focus",this.nW);this.load();var b=g.Og("STYLE");(g.Ag("HEAD")[0]||document.body).appendChild(b);g.je(this,function(){g.Sg(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},MPa=function(a){return a.player.getVideoData().D?"current":a.S?"new":"current"},H3=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},NPa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=F3(f,MPa(a))));I3(a,f)},
urlParams:{v:c},withCredentials:!0};a.S&&(c.urlParams.ptype="embedded");var d=b.tq;d&&(c.postParams={ad_tracking:d});if(b=g.Nqa(b))if(b=g.If(b),b=g.Ef(b))a.B=g.du(b,c)},I3=function(a,b,c){c=void 0===c?!0:c;
a.player.Xe("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&OPa(a);c=[];d=new g.gz(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().isMobile||(a.u=new g.W({G:"div",L:"ytp-ce-shadow"}),g.CM(a.player,a.u.element,4),a.C=new g.lL(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=PPa(a,e);if(f){a.i[e.id]=f;a.D[e.id]=e;g.CM(a.player,f.element,4);var h=new g.gz(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);QPa(a,
f,e)}else g.qy(new g.ow("buildEndscreenElement null",e))}a.player.Cd(c);a.xb()}},OPa=function(a){var b=g.hy(),c=g.iy();
c&&b&&a.endscreen.visualElement&&g.uy(void 0,c,b,[a.endscreen.visualElement])},PPa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ga:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.Mu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:J3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:K3(a,b.targetUrl),tabindex:"-1"},U:[{G:"div",Ga:["ytp-ce-video-title"].concat(g.la(c)),W:{dir:g.Jr(b.title||
"")},ya:b.title},{G:"div",L:"ytp-ce-video-duration",ya:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ga:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.Mu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:J3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:K3(a,
b.targetUrl),tabindex:"-1"},U:[{G:"div",Ga:["ytp-ce-playlist-title"].concat(g.la(c)),W:{dir:g.Jr(b.title||"")},ya:b.title},{G:"div",L:"ytp-ce-playlist-count",U:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",ya:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={G:"div",Ga:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.Mu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},
{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"a",Ga:["ytp-ce-channel-title","ytp-ce-link"],W:{href:K3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Jr(b.title||"")},ya:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",U:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",ya:b.subscribersText}:"",b.metadata?{G:"div",Ga:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],ya:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:J3(b)}]};c=new g.W(c);var d=g.Bg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.L(d,"ytp-ce-subscribe-button");if(a.player.V().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.SN(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Ga:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.Mu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},
{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-website-title",W:{dir:g.Jr(b.title||"")},ya:b.title},{G:"div",L:"ytp-ce-website-metadata",ya:b.metadata},{G:"a",Ga:["ytp-ce-website-goto","ytp-ce-link"],W:{href:K3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:J3(b)},{G:"div",
L:"ytp-ce-expanding-icon",W:RPa(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",U:[{G:"div",L:"ytp-ce-merchandise-price",ya:b.productPrice}]},b.additionalFeesText&&c.U.push({G:"div",L:"ytp-ce-merchandise-additional-fees",ya:b.additionalFeesText})),a={G:"div",Ga:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.Mu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",
U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-merchandise-title",W:{dir:g.Jr(b.title||"")},ya:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",ya:b.metadata},{G:"a",Ga:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:K3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},
{G:"div",L:"ytp-ce-expanding-image",W:J3(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",U:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",ya:b.callToAction||void 0}]}]},c=new g.W(a)}b.IS&&g.L(c.element,"ytp-ce-placeholder");return c},J3=function(a){if(a.SJ)var b=a.SJ.thumbnails;
return RPa(b?b[b.length-1].url:null)},RPa=function(a){return a?{style:"background-image: url("+a+")"}:{}},QPa=function(a,b,c){function d(m){m&&(b.Qa("blur",function(){"none"!=m.style.display&&a.X&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.L(b.element,"ytp-ce-force-expand"),L3(a,c.id,!0)):(g.or(b.element,"ytp-ce-force-expand"),g.or(b.element,"ytp-ce-element-hover"),L3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Qa("mouseenter",function(){M3(a,b,c)});
b.Qa("mouseleave",function(){N3(a,b,c)});
a.player.V().isMobile||b.Qa("click",function(){g.L(b.element,"ytp-ce-element-hover")});
b.Qa("click",function(m){SPa(a,c,m)});
b.Qa("keypress",function(m){SPa(a,c,m)});
b.Qa("focus",function(){M3(a,b,c)});
b.Qa("blur",function(){N3(a,b,c)});
b.Qa("touchstart",function(){M3(a,b,c)});
var l=g.Dg("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.or(b.element,"ytp-ce-element-hover");g.or(b.element,"ytp-ce-force-expand")});
b.Qa("keydown",function(m){a.X=9===m.keyCode&&!m.shiftKey});
d(g.Dg("ytp-sb-subscribe",b.element));d(g.Dg("ytp-sb-unsubscribe",b.element));b.Qa("focus",f);b.Qa("blur",h)},SPa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.mr(d,"ytp-ce-element");){g.mr(d,"subscribe-label")&&O3(a,b);
if(g.mr(d,"ytp-ce-channel-subscribe"))return;d=g.Tg(d)}if(!d||g.mr(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])N3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.lX)O3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.If(K3(a,b.targetUrl)),c=g.Ef(c),g.LL(c,void 0,b.sessionData);else{var e=a.player.getVideoData().D,f=function(){var h=K3(a,b.targetUrl),l=b.sessionData,m=g.Jt(h);e&&m&&(m.v||m.list)?a.player.Rj(m.v,l,m.list,!1):
g.KL(h,l)};
O3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},K3=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.lF(a)+b}else return"";return b},M3=function(a,b,c){g.mr(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.L(b.element,"ytp-ce-element-hover"):a.player.V().isMobile?(new g.I(function(){g.L(b.element,"ytp-ce-element-hover")},200)).start():g.L(b.element,"ytp-ce-element-hover"),P3(a,c.wS),L3(a,c.id,!0))},N3=function(a,b,c){g.or(b.element,"ytp-ce-element-hover");
g.or(b.element,"ytp-ce-force-expand");L3(a,c.id,!1)},L3=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.M(a.i[e].element,"ytp-ce-element-shadow-show",c)},P3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||H3(a))c&&c();else{b=TPa(a,b);var e=0,f=!1,h=new g.I(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Cv(b[a],d)}},O3=function(a,b,c){P3(a,b.clickUrls,c);
(a=g.iy())&&b.ES&&g.By(a,b.visualElement)},TPa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(UPa(b[d],c));return a},UPa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},VPa=function(a){return"string"===typeof a?a:""},Q3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},WPa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},R3=function(a){return a.value?a.value:null},S3=function(a){if(!a)return null;
var b=g.If(VPa(a.value));b=g.Ef(b);if(!b)return null;var c=Q3(a.target,XPa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new WPa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},YPa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},aQa=function(a){if(!a)return null;
var b=Q3(a.type,ZPa),c=Q3(a.trigger,$Pa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=S3(a?a:null);return b?new YPa(b,c,a):null},bQa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},dQa=function(a){return(a=cQa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},cQa=function(a,b){return g.Nb(a.action,b,void 0)},eQa=function(a,b){this.context=a;
this.i=b},U3=function(a){return a.customMessage?T3("div","iv-card-message",a.customMessage):""},V3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",L:"iv-card-image",W:{style:a},U:c}},W3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(T3("li","",c.value));return{G:"ul",L:"iv-card-meta-info",U:b}},T3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Jr(c);return{G:a,W:b,ya:c}},fQa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.py&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.py+");");c.dir=g.Jr(a.customMessage);var d=[{G:"span",ya:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",Ga:b,W:c,U:d}},X3=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},gQa=function(a,b){this.merchant=a;
this.price=b},hQa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},iQa=function(a,b){return b?b:hQa(a)?"current":"new"},Y3=function(a,b){g.E.call(this);
var c=this;this.element=a;this.context=b;this.bb=!1;this.Sa=new Map;this.Ua=new Map;this.context.J.addEventListener(g.Sz("annotations_module"),function(d){(d=c.Sa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.Tz("annotations_module"),function(d){(d=c.Ua.get(d))&&d.apply(c)})},Z3=function(a,b,c,d,e,f,h){a.context.i.Qa(b,"click",function(l){a.kC(c,d,e,f||[],h||0,l)});
a.context.i.Qa(b,"touchstart",function(){a.bb=!1});
a.context.i.Qa(b,"touchmove",function(){a.bb=!0})},jQa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},$3=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
YN:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
kB:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},c4=function(a,b,c){Y3.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Ka=this.rb=this.B=this.Yd=!1;this.xa=null;this.cards=[];this.kb=this.S=this.Ha=this.D=this.La=this.i=null;this.Z=[];this.K=this.Ce=this.Ba=null;this.I=0;this.Aa=new g.I(g.Ia,c.Y.Vd?4E3:3E3);g.H(this,this.Aa);this.Za=new g.I(g.Ia);g.H(this,this.Za);this.oa=new eQa(c,function(e,f,h,l,m,n){Z3(d,e,f,h,l,m,n)});
this.X=new g.W({G:"div",L:"iv-drawer",W:{id:"iv-drawer"},U:[{G:"div",L:"iv-drawer-header",W:{"aria-role":"heading"},U:[{G:"span",L:"iv-drawer-header-text"},{G:"button",Ga:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.H(this,this.X);this.C=this.X.element;this.Wa=new g.lL(this.X,330);g.H(this,this.Wa);this.jb=g.Dg("iv-drawer-header-text",this.C);this.u=g.Dg("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.rb&&a4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.rb=d.B)&&b4(d)})},kQa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){a4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){b4(a)});
var c=b.headerText;g.Vg(a.jb,c);a.S&&a.S.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ba=g.ey(b.trackingParams);a.K=g.ey(b.closeTrackingParams);a.Ce=g.ey(b.iconTrackingParams)},lQa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.Xz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.command),Gl:d.trackingParams?g.ey(d.trackingParams):null,Ui:e.trackingParams?
g.ey(e.trackingParams):null,Ce:f&&f.trackingParams?g.ey(f.trackingParams):null,imageUrl:e4(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.Xz(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,py:null,title:d.title?g.Xz(d.title):"",customMessage:d.callToAction?g.Xz(d.callToAction):"",url:d.command.urlEndpoint.url?S3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};f4(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.Xz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.endpoint),Gl:d.trackingParams?g.ey(d.trackingParams):null,Ui:e.trackingParams?g.ey(e.trackingParams):null,Ce:f&&f.trackingParams?
g.ey(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.Xz(d.customText):null,profileImageUrl:e4(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.Xz(d.channelName):"",metaInfo:[d.subscriberCountText?g.Xz(d.subscriberCountText):""],url:S3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};
f4(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.Xz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.action),Gl:d.trackingParams?g.ey(d.trackingParams):
null,Ui:e.trackingParams?g.ey(e.trackingParams):null,Ce:f&&f.trackingParams?g.ey(f.trackingParams):null,zx:e4(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.Xz(d.customMessage):null,playlistVideoCount:g.Xz(d.playlistVideoCount),title:d.playlistTitle?g.Xz(d.playlistTitle):"",metaInfo:[d.channelName?g.Xz(d.channelName):"",d.videoCountText?g.Xz(d.videoCountText):""],url:S3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:jQa(d.action)})};f4(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.Xz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.action),Gl:d.trackingParams?g.ey(d.trackingParams):null,Ui:e.trackingParams?g.ey(e.trackingParams):null,Ce:f&&f.trackingParams?g.ey(f.trackingParams):
null,zx:e4(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.Xz(d.lengthString):null,customMessage:d.customMessage?g.Xz(d.customMessage):null,title:d.videoTitle?g.Xz(d.videoTitle):"",metaInfo:[d.channelName?g.Xz(d.channelName):"",d.viewCountText?g.Xz(d.viewCountText):""],isLiveNow:!!d.badge,url:S3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:jQa(d.action)})};f4(a,b)}a.I++},e4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===
a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},d4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},nQa=function(a,b){if(b=mQa(a,b))b===a.i&&(a.i=null),a.J.removeCueRange(b.card.id),g.Sg(b.cD),g.Vb(a.cards,b),a.sy(),g4(a)},a4=function(a,b,c){if(!a.B){a.Wa.show();
a.La=new g.I(function(){g.L(a.context.J.getRootNode(),g.kT.IV_DRAWER_OPEN)},0);
a.La.start();a.xa=g.bv(a.u,"mousewheel",function(h){a.Aa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.iy();d&&a.Ba&&a.K&&g.zy(d,[a.Ba,a.K]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.EL||(f.EL=!0,oQa(a.context.logger,f.card.tracking.impression,b)),d&&g.zy(d,[f.card.Gl]);u3(a.J);c&&(a.D=new g.I(function(){a.Ha=a.S;a.kb.focus()},330),a.D.start())}},b4=function(a){a.B&&(a.Wa.hide(),g.cv(a.xa),a.xa=null,g.or(a.context.J.getRootNode(),g.kT.IV_DRAWER_OPEN),a.B=!1,u3(a.J),a.D&&a.D.stop(),a.D=new g.I(function(){a.Ha&&(a.Ha.focus(),a.Ha=null)},330),a.D.start())},
qQa=function(a){g.nr(a.element,[g.kT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.CM(a.J,a.C,5);pQa(a);a.S=g.Dg("ytp-cards-button",a.J.getRootNode());a.kb=g.Dg("iv-drawer-close-button",a.C);a.Yd=!0},pQa=function(a){var b=g.Dg("iv-drawer-close-button",a.C);
a.context.i.Qa(b,"click",a.kR,a);a.context.i.Qa(a.u,"touchend",function(){a.Aa.start()});
a.context.i.Qa(a.u,"scroll",a.wR,a);a.context.u.subscribe("onHideControls",function(){a.Ka=!0});
a.context.u.subscribe("onShowControls",function(){a.Ka=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ka=g.mr(a.J.getRootNode(),"ytp-autohide")});
a.Z.push(g.Jv("iv-button-shown",a.NS,a));a.Z.push(g.Jv("iv-button-hidden",a.MS,a));a.Z.push(g.Jv("iv-teaser-shown",a.QP,a));a.Z.push(g.Jv("iv-teaser-hidden",a.OS,a));a.Z.push(g.Jv("iv-teaser-clicked",a.PP,a))},f4=function(a,b){a.Yd||qQa(a);
nQa(a,b.id);var c=rQa(a,b);if(c){var d={card:b,cD:c.element,EL:!1},e=sQa(a,d);g.ac(a.cards,e,0,d);c.Ea(a.u,e);a.sy();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.i=d,g4(a),tQa(a,d),a4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&uQa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){uQa(a,d)}),g4(a))}},rQa=function(a,b){switch(b.type){case "simple":a=a.oa;
var c=b.displayDomain?{G:"div",L:"iv-card-image-text",ya:b.displayDomain}:void 0;var d=fQa(b);c={G:"div",Ga:["iv-card"],U:[{G:"a",L:"iv-click-target",W:{href:b.url?R3(b.url)||"":""},U:[V3(b.imageUrl,c),{G:"div",L:"iv-card-content",U:[T3("h2",void 0,b.title),d]}]}]};c=new g.W(c);X3(a,g.Cg("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.oa,c={G:"div",Ga:["iv-card","iv-card-channel"],U:[{G:"a",Ga:["iv-click-target"],W:{href:R3(b.url)||"","data-ytid":b.channelId},U:[V3(b.profileImageUrl),
{G:"div",L:"iv-card-content",U:[U3(b),{G:"h2",L:"iv-card-primary-link",ya:b.title},W3(b)]}]}]},c=new g.W(c),X3(a,g.Cg("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.oa,c={G:"div",Ga:["iv-card","iv-card-playlist"],U:[{G:"a",L:"iv-click-target",W:{href:R3(b.url)||""},U:[V3(b.zx,{G:"div",L:"iv-card-image-overlay",U:[{G:"span",L:"iv-card-playlist-video-count",ya:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",U:[U3(b),T3("h2","iv-card-primary-link",b.title),W3(b)]}]}]},c=new g.W(c),
X3(a,g.Cg("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.oa;var e=!g.Sb(b.offers);c=["iv-card"];d="";var f=fQa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",L:"iv-card-offer-price",ya:f.price}),f.merchant&&e.push({G:"div",L:"iv-card-offer-merchant",ya:f.merchant}),f={G:"div",U:e});e=b.url?R3(b.url)||"":"";c={G:"div",Ga:c,W:{tabindex:"0"},U:[{G:"a",Ga:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",U:[b.sponsored?{G:"div",L:"iv-card-sponsored",U:["Sponsored",{G:"div",L:"iv-ad-info-container",U:[{G:"div",L:"iv-ad-info",ya:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",U:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",W:{href:e},U:[T3("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.Og("span");g.Vg(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.kd(d,"adInfo");X3(a,g.Cg("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.oa,d=b.videoDuration?{G:"span",L:"iv-card-video-duration",ya:b.videoDuration}:void 0,f=b.isLiveNow?{G:"span",Ga:["yt-badge","yt-badge-live"],ya:"LIVE NOW"}:null,e={G:"div",Ga:["iv-card","iv-card-video"],U:[{G:"a",L:"iv-click-target",W:{href:(null===(c=b.url)||void 0===c?void 0:R3(c))||""},U:[V3(b.zx,d),{G:"div",L:"iv-card-content",U:[U3(b),T3("h2","iv-card-primary-link",b.title),W3(b),f]}]}]},c=new g.W(e),
X3(a,g.Cg("iv-click-target",c.element),b,b.url),c;default:return null}},sQa=function(a,b){if(0===a.cards.length)return 0;
a=g.Ob(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},vQa=function(a){return a.i?"productListing"===a.i.card.type:g.Rm(a.cards,function(b){return"productListing"===b.card.type})},g4=function(a){g.M(a.J.getRootNode(),"ytp-cards-shopping-active",vQa(a))},uQa=function(a,b){if(!g.mr(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.iy(),d=a.i?a.i.card.Ce:a.Ce;
c&&d&&g.Ay(c,[d]);a.i=b;g4(a)}if(c="none"!=a.element.style.display)a.context.J.V().N("html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.J.getPresentingPlayerType()?(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.J.getAdState();c&&b.card.teaserDurationMs&&a.J.zt(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Za.isActive()||((!a.B||!a.Aa.isActive()&&a.Ka)&&tQa(a,b),a.Za.start(910+b.card.teaserDurationMs))}},
tQa=function(a,b){a.X.yb?(b=new z3([0,
a.u.scrollTop],[0,b.cD.offsetTop],600,FPa),a.context.B.Qa(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Qa(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.CK(a.X,!0),a.u.scrollTop=b.cD.offsetTop,g.CK(a.X,!1))},h4=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},mQa=function(a,b){return g.Nb(a.cards,function(c){return c.card.id===b})},i4=function(a,b,c){Y3.call(this,a,b);
this.annotation=c;this.isActive=!1},wQa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},j4=function(a,b,c){i4.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.i=this.I=this.D=null},xQa=function(a,b){var c=void 0===c?0:c;
var d=DPa(b).width;g.qm(b,d);c=new B3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,EPa);g.H(a,c);a.context.B.Qa(c,"begin",function(){g.Dm(b,!0)});
c.play()},AQa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ga:["iv-branding-context-name"],ya:b.channel_name}),d=a.createElement({G:"div",Ga:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.SN(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.J),a.i.Ea(d));var f=a.createElement({G:"div",Ga:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ga:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Dm(h,!1);var l=a.createElement({G:"div",Ga:["branding-context-container-outer"]});l.appendChild(h);g.jm(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.I(function(){yQa(a,h,l)},500);
g.H(a,a.B);a.context.i.Qa(a.element,"mouseover",function(){zQa(a,h,l,f,b.image_height)});
a.context.i.Qa(a.element,"mouseout",function(){a.B.start()})}},zQa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.ym(b);a.i||(b.style.width=g.pm(f.width,!0),c.style.width=g.pm(f.width,!0));g.jm(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.jm(d,"right","1px");a.C=!0;g.Dm(b,!0);a.D=new g.I(function(){g.L(this.element,"iv-branding-active")},0,a);
a.D.start()}},yQa=function(a,b,c){g.or(a.element,"iv-branding-active");
a.I=new g.I(function(){g.Dm(b,!1);a.i||(c.style.width=g.pm(0,!0))},250);
a.I.start();a.C=!1},BQa=function(a,b,c,d,e,f,h){this.i=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.J=f;this.u=h},k4=function(a,b,c){i4.call(this,a,b,c);
var d=this;this.S=this.isCollapsed=this.X=!1;this.I=5E3;this.u=this.B=this.i=this.C=null;this.K=this.createElement({G:"div",Ga:["iv-promo-contents"]});this.D=new g.I(function(){d.i.setAttribute("aria-hidden","true");g.Dm(d.B,!1);g.Dm(d.u,!0)},700,this);
g.H(this,this.D)},CQa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=dQa(a.annotation),f=b.image_url;if(f){var h=a.createElement({G:"div",Ga:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({G:"span",L:"iv-promo-video-duration",ya:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",ya:b.playlist_length.toString()}),h.appendChild(f));e&&Z3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.bg(f,R3(e)),a.i=f):a.i=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",U:[{G:"strong",
ya:b.text_line_1}]});var m=a.createElement({G:"p",U:[{G:"span",L:"iv-promo-link",ya:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ga:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ga:["iv-button","iv-promo-button"],U:[{G:"span",L:"iv-button-content",ya:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&Z3(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.L(a.i,
"iv-click-target");e&&Z3(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",U:[{G:"span",ya:b.text_line_1}]}),m=a.createElement({G:"p",U:[{G:"strong",ya:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ga:["yt-badge","iv-promo-badge-live"],ya:"LIVE NOW"})),g.L(a.i,"iv-click-target"),e&&Z3(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.K.appendChild(a.i);p&&
a.K.appendChild(p);c=a.createElement({G:"div",L:"iv-promo-actions"});a.u=a.createElement({G:"button",Ga:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.i.Qa(a.u,"click",function(q){l4(a,5E3,q)});
c.appendChild(a.u);g.Dm(a.u,!1);a.context.i.Qa(a.element,"mouseover",a.cS,a);a.context.i.Qa(a.element,"mouseout",a.bS,a);a.context.i.Qa(a.element,"touchend",function(q){l4(a,5E3,q)});
a.B=a.createElement({G:"button",Ga:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.i.Qa(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.XR:a.WR,a);c.appendChild(a.B);g.nr(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.K);a.element.appendChild(c)},l4=function(a,b,c){c.stopPropagation();
DQa(a);EQa(a,b);a.i.focus()},FQa=function(a){a.isCollapsed||a.S||a.C||(g.L(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},DQa=function(a){a.D.stop();
a.isCollapsed&&(g.pr(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.Dm(a.u,!1),g.Dm(a.B,!0))},EQa=function(a,b){a.C||(a.C=g.Ih(function(){m4(this);
FQa(this)},b,a))},m4=function(a){a.C&&(g.B.clearTimeout(a.C),a.C=null)},GQa=function(a){this.J=a},oQa=function(a,b,c){b&&(c?n4(a,b.map(function(d){return g.Xq(d,c)})):n4(a,b))},n4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Cv(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},o4=function(a){g.PM.call(this,a);
var b=this;this.S=!1;this.loadNumber=0;this.I={};this.logger=new GQa(this.player);this.C=new g.aD(this);this.D=this.bl=null;this.events=new g.aD(this);this.K=this.i=null;this.X=[];g.H(this,this.C);this.C.T(this.player,"onVideoAreaChange",function(){b.ea("onVideoAreaChange")});
this.C.T(this.player,"onHideControls",function(){b.ea("onHideControls")});
this.C.T(this.player,"onShowControls",function(){b.ea("onShowControls")});
this.C.T(this.player,"resize",function(d){b.ea("resize",d)});
this.C.T(this.player,"presentingplayerstatechange",function(d){b.ea("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.RP,this);this.subscribe("resize",this.nA,this);this.player.V().S.subscribe("vast_info_card_add",this.RM,this);g.H(this,this.events);this.Z=this.createElement({G:"div",L:"video-custom-annotations"});this.u=new g.W({G:"div",Ga:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.CM(this.player,this.u.element,4);this.u.hide();this.B=new g.W({G:"div",Ga:["ytp-iv-video-content"]});g.H(this,this.B);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.Z);this.B.element.appendChild(a);this.Fq()&&this.load();var c=this.createElement({G:"style"});(g.Ag("HEAD")[0]||document.body).appendChild(c);g.je(this,function(){g.Sg(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},HQa=function(a){a=a.createElement({G:"div",
Ga:["annotation","annotation-type-custom"]});g.Dm(a,!1);return a},IQa=function(a,b){b=!b.isCued()&&!g.T(b,1024);
g.CK(a.u,b);g.CK(a.B,b)},JQa=function(a,b,c){a.S=!0;
a.D=g.du(b,c)},KQa=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ma(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(KQa(a,e))}return c},NQa=function(a){var b=a.player.getVideoData();
if(b.Ua){var c=a.player.V().S.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Vt(h)&&h.responseXML?h.responseXML:null)&&p4(a,h)}};
g.tv()&&(d.onFinish=LQa(a,d.onFinish));d.postParams={ic_only:"1"};MQa(d,c);a.S=!0;g.du(b.Ua,d)}}},MQa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Wu&&(a.postParams.ic_coll=b.Wu);b.zy&&(a.postParams.ic_xml=b.zy);b.Cx&&(a.postParams.ic_track=b.Cx)},OQa=function(a){var b=new g.W({G:"div"});
g.Dm(b.element,!1);var c=new c4(a.player,b.element,q4(a));g.H(c,b);b.Ea(a.u.element);c.ix();return c},q4=function(a){if(!a.K){var b=new C3(a);
g.H(a,b);var c=new g.Rk(a);g.H(a,c);a.K=new BQa(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.Vd)}return a.K},p4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.iy();if(e){var f=g.hy();f&&g.uy(void 0,e,f,[g.ey(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=KQa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=Q3(f.type,PQa),p=Q3(f.style,QQa),q=VPa(f.data),t=0!==q.length?JSON.parse(q):{};var u=f.action;f=aQa;if(null==u)var x=null;else if(g.La(u)){l=[];for(var y=g.r(u),z=y.next();!z.done;z=y.next()){var C=f(z.value);
C&&l.push(C)}x=l}else{var G=f(u);x=G?[G]:[]}e=m&&n?new bQa(m,n,p,x,t):null}else e=null}catch(Aa){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var F=HQa(f),J=null;switch(l.type){case "branding":if(f.player.V().Db)break;f.u.element.appendChild(F);J=new j4(F,q4(f),l);break;case "promotion":g.CM(f.player,F,4),J=new k4(F,q4(f),l)}J&&J.ix();if(f=J)g.H(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=OQa(a),g.H(a,a.i));if("card"===e.type){c=a.i;var U=e&&e.data&&e.data.card_type;
f=e.data;if(U)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,YN:l.teaser_impression,kB:l.teaser_click},F=f.tracking_params||{},J=null,U){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Gl:F.card?g.ey(F.card):null,Ui:F.teaser?g.ey(F.teaser):null,Ce:F.icon?g.ey(F.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:S3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};f4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Gl:F.card?g.ey(F.card):
null,Ui:F.teaser?g.ey(F.teaser):null,Ce:F.icon?g.ey(F.icon):null,zx:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:S3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};f4(c,e);break;case "productListing":f.signin_url&&(J=S3({target:"current",value:f.signin_url}));U=[];for(var K=f.offers||[],Y=0;Y<K.length;Y++)U.push(new gQa(g.qg(K[Y].merchant),g.qg(K[Y].price)));e={id:e.id,
timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Gl:F.card?g.ey(F.card):null,Ui:F.teaser?g.ey(F.teaser):null,Ce:F.icon?g.ey(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,py:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:
null,url:S3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Xca:J,Wca:f.signin_title?f.signin_title:void 0,Vca:f.signin_message?f.signin_message:void 0,offers:U};f4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Gl:F.card?g.ey(F.card):null,Ui:F.teaser?g.ey(F.teaser):
null,Ce:F.icon?g.ey(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,py:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:S3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};f4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||
!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Gl:F.card?g.ey(F.card):null,Ui:F.teaser?g.ey(F.teaser):null,Ce:F.icon?g.ey(F.icon):null,zx:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:S3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},f4(c,e)}}else kQa(a.i,e);c=!0}}c&&(u3(a.player),a.nA())},RQa=function(a,b){var c=!1;
a.i||(a.i=OQa(a),g.H(a,a.i));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(lQa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.Xz(b.headerText):"",g.Vg(c.jb,d),c.S&&c.S.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ba=b.trackingParams?g.ey(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.ey(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Ce=b.icon.infoCardIconRenderer.trackingParams?
g.ey(b.icon.infoCardIconRenderer.trackingParams):null,u3(a.player),a.nA())},SQa=function(a,b,c,d,e){if(!a.player.V().Db){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new YPa("openUrl","click",new WPa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Xz(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.Xz(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Xz(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.Xz(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.Xz(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.Xz(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new bQa(c,"branding","branding",f,d);l=HQa(a);a.u.element.appendChild(l);f=new j4(l,q4(a),f);f.ix();g.H(f,f);a.I[c]=f}},LQa=function(a,b){return function(){var c=g.Ba.apply(0,arguments);
a.isDisposed()||a.X.push(g.zv.Of(function(){b.apply(null,g.la(c))}))}},TQa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.vM.prototype.zt=g.ca(17,function(a,b){var c=g.dN(this.vb());c&&c.zt(a,b)});
var w3={},x3=null;g.Ua(z3,g.zr);g.k=z3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.i)this.progress=0,this.coords=this.u;else if(this.Dc())return!1;y3(this);this.startTime=a=g.Ta();-1==this.i&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.jA();this.wi("play");-1==this.i&&this.wi("resume");this.i=1;var b=g.Pa(this);b in w3||(w3[b]=this);HPa();IPa(this,a);return!0};
g.k.stop=function(a){y3(this);this.i=0;a&&(this.progress=1);JPa(this,this.progress);this.wi("stop");this.Dw()};
g.k.pause=function(){this.Dc()&&(y3(this),this.i=-1,this.wi("pause"))};
g.k.va=function(){0==this.i||this.stop(!1);this.wi("destroy");z3.je.va.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.jC=function(){this.wi("animate")};
g.k.wi=function(a){this.dispatchEvent(new KPa(a,this))};
g.Ua(KPa,g.ke);g.Ua(A3,z3);A3.prototype.C=g.Ia;A3.prototype.jC=function(){this.C();A3.je.jC.call(this)};
A3.prototype.Dw=function(){this.C();A3.je.Dw.call(this)};
A3.prototype.jA=function(){this.C();A3.je.jA.call(this)};
g.Ua(B3,A3);B3.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.v(C3,g.E);C3.prototype.Qa=function(a,b,c,d){c=(0,g.D)(c,d||this.u);a=g.bv(a,b,c);this.i.push(a);return a};
C3.prototype.Qz=function(a,b,c,d){c=(0,g.D)(c,d||this.u);a=g.kv(a,b,c);this.i.push(a);return a};
C3.prototype.lc=function(a){g.cv(a);g.Vb(this.i,a)};
C3.prototype.va=function(){g.cv(this.i);this.i.length=0;g.E.prototype.va.call(this)};g.v(G3,g.PM);g.k=G3.prototype;g.k.load=function(){g.PM.prototype.load.call(this);if(!H3(this)){var a=g.Oqa(this.player.getVideoData());a?(a=F3(a,MPa(this)),I3(this,a,!1)):NPa(this)}};
g.k.unload=function(){I3(this,null);this.B&&(this.B.abort(),this.B=null);g.PM.prototype.unload.call(this)};
g.k.jf=function(a,b){return H3(this)?"loadCustomEndscreenRenderer"===a?(a=F3(b,"new"),I3(this,a),!0):null:null};
g.k.getOptions=function(){return H3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.xb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<UQa.length;f++){var h=Math.abs(b.width-UQa[f]);if(-1===e||d>=h)e=f,d=h}d=VQa[e];this.u&&g.jm(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.xm(e.element,Math.round(h.width*a.width),f);g.qm(e.element,m,n);g.pr(e.element,WQa);m=h.left+h.width/2;h=h.top+l/2;g.L(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.pr(e.element,VQa);g.L(e.element,d);(e=g.Bg(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.jm(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())P3(this,this.endscreen.impressionUrls),(a=g.iy())&&this.endscreen.visualElement&&g.vy(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.D[a];g.L(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.L(b,"ytp-ce-shown");P3(this,c.impressionUrls);(b=g.iy())&&g.vy(b,c.visualElement,void 0);this.player.V().u&&this.player.Ma("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.or(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.or(b,"ytp-ce-shown");this.player.V().u&&this.player.Ma("endscreenelementhidden",a)}};
g.k.nW=function(a){var b=this;a.target===window&&(new g.I(function(){for(var c=g.r(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.pr(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var UQa=[346,426,470,506,570,640,853,1280,1920],VQa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),WQa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var XPa={u1:"current",F7:"new"};var ZPa={CLOSE:"close",Y7:"openUrl",SUBSCRIBE:"subscribe"},$Pa={zZ:"click",CLOSE:"close",W2:"hidden",x9:"rollOut",y9:"rollOver",p$:"shown"};var QQa={BY:"anchored",LO:"branding",CHANNEL:"channel",t1:"cta",Z2:"highlightText",t4:"label",PLAYLIST:"playlist",Q8:"popup",y$:"speech",SUBSCRIBE:"subscribe",Q$:"title",VIDEO:"video",wba:"website"},PQa={LO:"branding",mZ:"card",L1:"drawer",Y2:"highlight",V5:"marker",b9:"promotion",TEXT:"text",Uba:"widget"};g.v(Y3,g.E);g.k=Y3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.gz(a,b,{id:c,namespace:"annotations_module"});d&&this.Sa.set(a,d);e&&this.Ua.set(a,e);this.context.J.Cd([a])};
g.k.ix=function(){this.context.u.subscribe("resize",this.sy,this)};
g.k.kC=function(a,b,c,d,e,f){if(this.bb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Sg(this.element)};
g.k.sy=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=R3(a);if(f){var h=iQa(f,a.target),l=function(){a.i&&e.context.J.pauseVideo();var m=e.context.videoData.D||!1,n=g.Jt(f||"");m&&n&&(n.v||n.list)?e.context.J.Rj(n.v,b,n.list,!1):g.LL(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);n4(this.context.logger,c,l,d);hQa(f)||(c=g.iy(),d=b.itct,c&&d&&g.By(c,g.ey(d)))}};
g.k.va=function(){this.Sa.clear();this.Ua.clear();g.E.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.H(this,a);return a.element};g.v(c4,Y3);g.k=c4.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.ym(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.sy=function(){var a=this.isAvailable();g.Dm(this.element,a);g.M(this.context.J.getRootNode(),g.kT.IV_DRAWER_ENABLED,a);u3(this.J)};
g.k.destroy=function(){this.J.zt(!1);try{this.J.getRootNode().removeChild(this.C)}catch(a){}g.Kv(this.Z);g.cv(this.xa);this.La&&this.La.dispose();this.D&&this.D.dispose();Y3.prototype.destroy.call(this)};
g.k.kR=function(){if(this.B){n4(this.context.logger,h4(this).tracking.close);var a=g.iy();a&&this.K&&g.By(a,this.K);b4(this)}};
g.k.wR=function(){g.M(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.NS=function(){var a=g.iy(),b=h4(this);b=b?b.Ce:this.Ce;a&&b&&g.zy(a,[b])};
g.k.MS=function(){var a=g.iy(),b=h4(this);b=b?b.Ce:this.Ce;a&&b&&g.Ay(a,[b])};
g.k.QP=function(){var a=h4(this);n4(this.context.logger,a.tracking.YN);var b=g.iy();b&&a&&g.zy(b,[a.Ui,a.Ce])};
g.k.OS=function(){var a=g.iy(),b=h4(this);a&&b&&g.Ay(a,[b.Ui])};
g.k.PP=function(a){var b=h4(this),c=g.iy();this.i?a?(a=this.context.logger,n4(a,b.tracking.kB),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Ui&&g.By(c,b.Ui)):(a=this.context.logger,n4(a,b.tracking.kB),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Ce&&g.By(c,b.Ce)):(a=this.context.logger,n4(a,b.tracking.kB),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Ce&&g.By(c,this.Ce))};g.v(i4,Y3);i4.prototype.ix=function(){Y3.prototype.ix.call(this);wQa(this)};
i4.prototype.show=function(){Y3.prototype.show.call(this);var a=g.iy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.zy(a,[g.ey(b.itct)])};
i4.prototype.hide=function(){Y3.prototype.hide.call(this);var a=g.iy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Ay(a,[g.ey(b.itct)])};g.v(j4,i4);
j4.prototype.show=function(){if(!this.isActive){i4.prototype.show.call(this);if(!this.K){g.L(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ga:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Dm(this.u,!1);var b=this.createElement({G:"div",Ga:["branding-img-container"]});b.appendChild(this.u);this.element.appendChild(b);(b=dQa(this.annotation))&&Z3(this,this.u,b,this.annotation.id,
a.session_data);AQa(this,a);this.K=!0}g.Dm(this.element,!0);this.isActive=!0;this.u&&xQa(this,this.u)}};
j4.prototype.hide=function(){this.isActive&&(i4.prototype.hide.call(this),g.Dm(this.element,!1),this.isActive=!1)};
j4.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);i4.prototype.destroy.call(this)};g.v(k4,i4);g.k=k4.prototype;g.k.show=function(){this.isActive||(i4.prototype.show.call(this),this.X||(CQa(this),this.X=!0),g.Dm(this.element,!0),g.Ih(function(){g.or(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,m4(this),DQa(this),EQa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.L(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.kC=function(a,b,c,d,e,f){return this.isCollapsed?!1:i4.prototype.kC.call(this,a,b,c,d,e,f)};
g.k.cS=function(a){this.S=!0;l4(this,500,a)};
g.k.bS=function(){this.S=!1;FQa(this)};
g.k.WR=function(a){a.stopPropagation();this.hide()};
g.k.XR=function(a){a.stopPropagation();m4(this);this.isCollapsed=!0;g.L(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();i4.prototype.destroy.call(this)};g.v(o4,g.PM);g.k=o4.prototype;g.k.jf=function(a,b){if(!TQa(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.U1(b))&&p4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(nQa(this.i,b),u3(this.player)),!0}return null};
g.k.getOptions=function(){return TQa(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Fq=function(){var a=this.player.V(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.mL||a.S.get(b.videoId)||g.yG(b)||g.zG(b)?!0:!1};
g.k.nA=function(){if(this.B){var a=this.player.eb().getVideoContentRect(!0);g.xm(this.B.element,a.width,a.height);g.qm(this.B.element,a.left,a.top)}if(this.i){var b=this.player.qj();a=this.i;b=b.width;g.M(a.C,"iv-drawer-small",426>=b);g.M(a.C,"iv-drawer-big",1280<=b)}};
g.k.RP=function(a){IQa(this,a.state);g.T(a.state,2)&&(this.Bh()&&this.rk()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.zt(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Vt(h)&&h.responseXML?h.responseXML:null)&&(p4(b,h),g.L(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.PM.prototype.load.call(this);IQa(this,this.player.zb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.tv()&&(a=LQa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.D=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().S.get(d);f&&MQa(e,f);f=f&&(f.zy||f.Wu);if(!c.Xo||f)c.Ua?JQa(this,c.Ua,e):(this.bl=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.bl));
g.CM(this.player,this.B.element,4);this.nA();(f=g.yG(c))&&RQa(this,f);(f=g.zG(c))&&f.featuredChannel&&SQa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ua&&(this.bl&&(this.player.removeEventListener("videodatachange",this.bl),this.bl=null),JQa(this,b.Ua,a))};
g.k.unload=function(){this.player.Xe("annotations_module");for(var a=g.r(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.K=null;this.i&&(this.i.destroy(),this.i=null,u3(this.player));this.S=!1;this.D&&(this.D.abort(),this.D=null);this.I={};this.u.hide();g.PM.prototype.unload.call(this);this.B.detach();this.bl&&(this.player.removeEventListener("videodatachange",this.bl),this.bl=null)};
g.k.RM=function(a){a===this.player.getVideoData().videoId&&(this.loaded?NQa(this):this.load())};
g.k.Bh=function(){return!!this.i&&this.i.isAvailable()};
g.k.rk=function(){this.Bh();return!!this.i&&this.i.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Bh();this.i&&(a?c?a4(this.i,c,b):a4(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):b4(this.i))};
g.k.zt=function(a,b){this.player.ea(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.va=function(){this.player.V().S.unsubscribe("vast_info_card_add",this.RM,this);g.or(this.player.getRootNode(),g.kT.IV_DRAWER_OPEN);for(var a=this.X,b=0,c=a.length;b<c;b++)g.zv.oi(a[b]);this.X.length=0;g.PM.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.H(this,a);return a.element};g.OM("annotations_module",o4);g.OM("creatorendscreen",G3);})(_yt_player);
