(function(g){var window=this;'use strict';var lTa=function(a,b){return g.Ee(a,b)},mTa=function(a,b){b=b instanceof g.Df?b:g.Jf(b,/^data:image\//i.test(b));
a.src=g.Ef(b)},O6=function(a){g.Lk(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Ta()).toString(36));
return a},P6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.Qk(a.u,b,c)},nTa=function(a){if(a===g.Fo)throw Error("ES6 Iteration protocol does NOT adjust control flow when StopIteration is thrown from callback helper functions. If your code relies on this behavior, consider throwing a different error and catching it to terminate iteration.");
throw a;},oTa=function(a){if(a instanceof g.Do)return a;
if("function"==typeof a.Jg)return a.Jg(!1);if(g.La(a)){var b=0,c=new g.Do;c.next=function(){for(;;){if(b>=a.length)return g.f2;if(b in a)return g.Eo(a[b++]);b++}};
var d=c.next;c.Aj=function(){return g.Go(d.call(c))};
return c}throw Error("Not implemented");},pTa=function(a,b,c){if(g.La(a))try{g.lc(a,b,c)}catch(e){nTa(e)}else for(a=oTa(a);;){var d=void 0;
try{d=a.Aj()}catch(e){if(e===g.Fo)break;throw e;}try{b.call(c,d,void 0,a)}catch(e){nTa(e)}}},qTa=function(a,b){var c=[];
pTa(b,function(d){try{var e=g.Wr.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Vr(e)&&c.push(d)},a);
return c},rTa=function(a,b){qTa(a,b).forEach(function(c){g.Wr.prototype.remove.call(this,c)},a)},sTa=function(a){if(a.xa){if(a.xa.locationOverrideToken)return{locationOverrideToken:a.xa.locationOverrideToken};
if(null!=a.xa.latitudeE7&&null!=a.xa.longitudeE7)return{latitudeE7:a.xa.latitudeE7,longitudeE7:a.xa.longitudeE7}}return null},tTa=function(a,b){g.Rb(a,b)||a.push(b)},Q6=function(a){var b=0,c;
for(c in a)b++;return b},uTa=function(a){try{return g.B.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},R6=function(a){if(g.B.JSON)try{return g.B.JSON.parse(a)}catch(b){}return uTa(a)},vTa=function(a,b,c,d){var e=new g.wk(null,void 0);
a&&g.xk(e,a);b&&g.yk(e,b);c&&g.zk(e,c);d&&(e.K=d);return e},S6=function(a,b){g.Hv[a]=!0;
var c=g.Fv();c&&c.publish.apply(c,arguments);g.Hv[a]=!1},T6=function(a){this.name=this.id="";
this.clientName="UNKNOWN_INTERFACE";this.app="";this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.wr;this.model=this.brand="";this.year=0;this.chipset=this.osVersion=this.os="";this.mdxDialServerType="MDX_DIAL_SERVER_TYPE_UNKNOWN";a&&(this.id=a.id||a.name,this.name=a.name,this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=
a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",wTa(this,a.capabilities||""),xTa(this,a.experiments||""),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN",a=a.deviceInfo)&&(a=JSON.parse(a),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",
this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN")},wTa=function(a,b){a.capabilities.clear();
g.ep(b.split(","),g.Sa(lTa,yTa)).forEach(function(c){a.capabilities.add(c)})},xTa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},U6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},V6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},zTa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},ATa=function(a){return new U6(a)},BTa=function(a){return Array.isArray(a)?g.Qm(a,ATa):[]},W6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},X6=function(a){return Array.isArray(a)?"["+g.Qm(a,W6).join(",")+"]":"null"},Y6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},CTa=function(a){return g.Qm(a,function(b){return{key:b.id,
name:b.name}})},Z6=function(a,b){return g.Nb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},$6=function(a,b){return g.Nb(a,function(c){return V6(c,b)})},DTa=function(){var a=(0,g.Dy)();
a&&rTa(a,a.i.Jg(!0))},a7=function(){var a=g.Gy("yt-remote-connected-devices")||[];
g.ic(a);return a},ETa=function(a){if(g.Sb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Qm(a,function(d,e){return 0==e?d:d.substring(c.length)})},FTa=function(a){g.Fy("yt-remote-connected-devices",a,86400)},c7=function(){if(b7)return b7;
var a=g.Gy("yt-remote-device-id");a||(a=Y6(),g.Fy("yt-remote-device-id",a,31536E3));for(var b=a7(),c=1,d=a;g.Rb(b,d);)c++,d=a+"#"+c;return b7=d},d7=function(){var a=a7(),b=c7();
g.Rb(a,b);g.Iy()&&g.kc(a,b);a=ETa(a);if(g.Sb(a))try{g.qu("remote_sid")}catch(c){}else try{g.ou("remote_sid",a.join(","),-1)}catch(c){}},GTa=function(){return g.Gy("yt-remote-session-browser-channel")},HTa=function(){return g.Gy("yt-remote-local-screens")||[]},ITa=function(){g.Fy("yt-remote-lounge-token-expiration",!0,86400)},JTa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Qm(HTa(),function(d){return d.loungeToken}),c=g.Qm(a,function(d){return d.loungeToken});
g.Rm(c,function(d){return!g.Rb(b,d)})&&ITa();
g.Fy("yt-remote-local-screens",a,31536E3)},KTa=function(a,b){g.Fy("yt-remote-session-browser-channel",a);
g.Fy("yt-remote-session-screen-id",b);a=a7();b=c7();g.Rb(a,b)||a.push(b);FTa(a);d7()},e7=function(a){a||(g.Hy("yt-remote-session-screen-id"),g.Hy("yt-remote-session-video-id"));
d7();a=a7();g.Vb(a,c7());FTa(a)},LTa=function(){if(!f7){var a=g.fs();
a&&(f7=new g.Qr(a))}},MTa=function(){LTa();
return f7?!!f7.get("yt-remote-use-staging-server"):!1},g7=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},NTa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},OTa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},h7=function(a){a.length?PTa(a.shift(),function(){h7(a)}):i7()},QTa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},PTa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.Tj(d,g.Er(a));(document.head||document.documentElement).appendChild(d)},RTa=function(){var a=g7(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},i7=function(){var a=OTa();
a&&a(!1,"No cast extension found")},j7=function(){if(STa){var a=2,b=OTa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;PTa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",i7,c)}},TTa=function(){j7();
var a=RTa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");h7(a)},VTa=function(){j7();
var a=RTa();a.push.apply(a,g.la(UTa.map(QTa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");h7(a)},k7=function(a,b,c){g.E.call(this);
this.I=null!=c?(0,g.D)(a,c):a;this.Tf=b;this.D=(0,g.D)(this.lQ,this);this.i=!1;this.u=0;this.B=this.Mb=null;this.C=[]},l7=function(a,b,c){g.E.call(this);
this.C=null!=c?a.bind(c):a;this.Tf=b;this.B=null;this.i=!1;this.u=0;this.Mb=null},m7=function(a){a.Mb=g.Ih(function(){a.Mb=null;
a.i&&!a.u&&(a.i=!1,m7(a))},a.Tf);
var b=a.B;a.B=null;a.C.apply(null,b)},n7=function(){},o7=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.B.setTimeout(function(){a()},b)},q7=function(a){p7.dispatchEvent(new WTa(p7,a))},WTa=function(a,b){g.ke.call(this,"statevent",a);
this.stat=b},r7=function(a,b,c,d){this.i=a;
this.B=b;this.S=c;this.K=d||1;this.u=45E3;this.C=new g.Rk(this);this.I=new g.Hh;this.I.setInterval(250)},YTa=function(a,b,c){a.Kt=1;
a.Um=O6(b.clone());a.wq=c;a.D=!0;XTa(a,null)},s7=function(a,b,c,d,e){a.Kt=1;
a.Um=O6(b.clone());a.wq=null;a.D=c;e&&(a.FN=!1);XTa(a,d)},XTa=function(a,b){a.wt=Date.now();
t7(a);a.Eo=a.Um.clone();P6(a.Eo,"t",a.K);a.zB=0;a.Kf=a.i.rD(a.i.nx()?b:null);0<a.nC&&(a.NA=new l7((0,g.D)(a.HO,a,a.Kf),a.nC));a.C.Qa(a.Kf,"readystatechange",a.mQ);b=a.Wo?g.Le(a.Wo):{};a.wq?(a.xB="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.Kf.send(a.Eo,a.xB,a.wq,b)):(a.xB="GET",a.FN&&!g.Jg&&(b.Connection="close"),a.Kf.send(a.Eo,a.xB,null,b));a.i.Bj(1)},$Ta=function(a,b){var c=a.zB,d=b.indexOf("\n",c);
if(-1==d)return u7;c=Number(b.substring(c,d));if(isNaN(c))return ZTa;d+=1;if(d+c>b.length)return u7;b=b.substr(d,c);a.zB=d+c;return b},bUa=function(a,b){a.wt=Date.now();
t7(a);var c=b?window.location.hostname:"";a.Eo=a.Um.clone();g.Lk(a.Eo,"DOMAIN",c);g.Lk(a.Eo,"t",a.K);try{a.Pj=new ActiveXObject("htmlfile")}catch(m){v7(a);a.Om=7;q7(22);w7(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in x7)f=x7[f];else if(f in aUa)f=x7[f]=aUa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
x7[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Zf(g.vf("b/12014412"),d);a.Pj.open();a.Pj.write(g.Vf(c));a.Pj.close();a.Pj.parentWindow.m=(0,g.D)(a.dW,a);a.Pj.parentWindow.d=(0,g.D)(a.QM,a,!0);a.Pj.parentWindow.rpcClose=(0,g.D)(a.QM,a,!1);c=a.Pj.createElement("DIV");a.Pj.parentWindow.document.body.appendChild(c);d=g.If(a.Eo.toString());d=g.pg(g.Ef(d));d=g.Zf(g.vf("b/12014412"),'<iframe src="'+d+'"></iframe>');g.ag(c,d);a.i.Bj(1)},t7=function(a){a.dH=Date.now()+
a.u;
cUa(a,a.u)},cUa=function(a,b){if(null!=a.Vt)throw Error("WatchDog timer not null");
a.Vt=o7((0,g.D)(a.kW,a),b)},y7=function(a){a.Vt&&(g.B.clearTimeout(a.Vt),a.Vt=null)},w7=function(a){a.i.rf()||a.np||a.i.Yx(a)},v7=function(a){y7(a);
g.he(a.NA);a.NA=null;a.I.stop();g.Tk(a.C);if(a.Kf){var b=a.Kf;a.Kf=null;b.abort();b.dispose()}a.Pj&&(a.Pj=null)},z7=function(a,b){try{a.i.IM(a,b),a.i.Bj(4)}catch(c){}},eUa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;dUa(a,b,function(h){h?c(!0):g.B.setTimeout(function(){eUa(a,b,c,d,f)},f)})}},dUa=function(a,b,c){var d=new Image;
d.onload=function(){try{A7(d),c(!0)}catch(e){}};
d.onerror=function(){try{A7(d),c(!1)}catch(e){}};
d.onabort=function(){try{A7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{A7(d),c(!1)}catch(e){}};
g.B.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
mTa(d,a)},A7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},fUa=function(a){this.i=a;
this.u=new n7},gUa=function(a){var b=B7(a.i,a.Tu,"/mail/images/cleardot.gif");
O6(b);eUa(b.toString(),5E3,(0,g.D)(a.dR,a),3,2E3);a.Bj(1)},D7=function(a){var b=a.i.X;
if(null!=b)q7(5),b?(q7(11),C7(a.i,a,!1)):(q7(12),C7(a.i,a,!0));else if(a.ph=new r7(a,void 0,void 0,void 0),a.ph.Wo=a.oC,b=a.i,b=B7(b,b.nx()?a.Du:null,a.pC),q7(5),!g.Dc||g.vc(10))P6(b,"TYPE","xmlhttp"),s7(a.ph,b,!1,a.Du,!1);else{P6(b,"TYPE","html");var c=a.ph;a=!!a.Du;c.Kt=3;c.Um=O6(b.clone());bUa(c,a)}},E7=function(a,b,c){this.i=1;
this.u=[];this.C=[];this.D=new n7;this.S=a||null;this.X=null!=b?b:null;this.I=c||!1},hUa=function(a,b){this.i=a;
this.map=b;this.context=null},iUa=function(a,b,c,d){g.ke.call(this,"timingevent",a);
this.size=b;this.bx=d},jUa=function(a){g.ke.call(this,"serverreachability",a)},mUa=function(a){kUa(a);
if(3==a.i){var b=a.pw++,c=a.Sy.clone();g.Lk(c,"SID",a.B);g.Lk(c,"RID",b);g.Lk(c,"TYPE","terminate");F7(a,c);b=new r7(a,a.B,b,void 0);b.Kt=2;b.Um=O6(c.clone());mTa(new Image,b.Um.toString());b.wt=Date.now();t7(b)}lUa(a)},nUa=function(a){a.DR(1,0);
a.Sy=B7(a,null,a.qC);G7(a)},kUa=function(a){a.Ym&&(a.Ym.abort(),a.Ym=null);
a.Ie&&(a.Ie.cancel(),a.Ie=null);a.El&&(g.B.clearTimeout(a.El),a.El=null);H7(a);a.Tg&&(a.Tg.cancel(),a.Tg=null);a.vn&&(g.B.clearTimeout(a.vn),a.vn=null)},oUa=function(a,b){if(0==a.i)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new hUa(a.fT++,b));2!=a.i&&3!=a.i||G7(a)},pUa=function(a){var b=0;
a.Ie&&b++;a.Tg&&b++;return b},G7=function(a){a.Tg||a.vn||(a.vn=o7((0,g.D)(a.OM,a),0),a.ls=0)},rUa=function(a,b){if(1==a.i){if(!b){a.pw=Math.floor(1E5*Math.random());
b=a.pw++;var c=new r7(a,"",b,void 0);c.Wo=a.Zj;var d=I7(a),e=a.Sy.clone();g.Lk(e,"RID",b);g.Lk(e,"CVER","1");F7(a,e);YTa(c,e,d);a.Tg=c;a.i=2}}else 3==a.i&&(b?qUa(a,b):0==a.u.length||a.Tg||qUa(a))},qUa=function(a,b){if(b)if(6<a.pp){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.pw-1;b=I7(a)}else c=b.S,b=b.wq;else c=a.pw++,b=I7(a);var d=a.Sy.clone();g.Lk(d,"SID",a.B);g.Lk(d,"RID",c);g.Lk(d,"AID",a.Os);F7(a,d);c=new r7(a,a.B,c,a.ls+1);c.Wo=a.Zj;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Tg=c;YTa(c,d,b)},F7=function(a,b){a.Lf&&(a=a.Lf.iK())&&g.se(a,function(c,d){g.Lk(b,d,c)})},I7=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.pp&&0<b){var d=a.u[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={Wq:e.Wq},f++){e.Wq=a.u[f].i;var h=a.u[f].map;e.Wq=6>=a.pp?f:e.Wq-d;try{g.se(h,function(l){return function(m,n){c.push("req"+l.Wq+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.Wq+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},sUa=function(a){a.Ie||a.El||(a.K=1,a.El=o7((0,g.D)(a.MM,a),0),a.Lr=0)},J7=function(a){if(a.Ie||a.El||3<=a.Lr)return!1;
a.K++;a.El=o7((0,g.D)(a.MM,a),tUa(a,a.Lr));a.Lr++;return!0},C7=function(a,b,c){a.vB=c;
a.bk=b.ql;a.I||nUa(a)},H7=function(a){null!=a.zp&&(g.B.clearTimeout(a.zp),a.zp=null)},tUa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},K7=function(a,b){if(2==b||9==b){var c=null;
a.Lf&&(c=null);var d=(0,g.D)(a.nX,a);c||(c=new g.wk("//www.google.com/images/cleardot.gif"),O6(c));dUa(c.toString(),1E4,d)}else q7(2);uUa(a,b)},uUa=function(a,b){a.i=0;
a.Lf&&a.Lf.vJ(b);lUa(a);kUa(a)},lUa=function(a){a.i=0;
a.bk=-1;if(a.Lf)if(0==a.C.length&&0==a.u.length)a.Lf.eD();else{g.Yb(a.C);var b=g.Yb(a.u);a.C.length=0;a.u.length=0;a.Lf.eD(b)}},B7=function(a,b,c){var d=g.Mk(c);
if(""!=d.i)b&&g.yk(d,b+"."+d.i),g.zk(d,d.B);else{var e=window.location;d=vTa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.yv&&g.se(a.yv,function(f,h){g.Lk(d,h,f)});
g.Lk(d,"VER",a.pp);F7(a,d);return d},vUa=function(){},wUa=function(){this.i=[];
this.u=[]},xUa=function(a,b){this.action=a;
this.params=b||{}},L7=function(a,b){g.E.call(this);
this.i=new g.I(this.UV,0,this);g.H(this,this.i);this.Tf=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.D)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.D)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},M7=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.xa=a;this.I=b;this.B=new g.Pr;this.u=new L7(this.RW,this);this.i=null;this.Z=!1;this.D=null;this.X="";this.S=this.C=0;this.K=[];this.Aa=c;this.oa=d;this.Ba=e},yUa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.vB,sessionId:a.i.B,arrayId:a.i.Os}},zUa=function(a,b){a.S=b||0;
a.u.stop();N7(a);a.i&&(3==a.i.getState()&&rUa(a.i),mUa(a.i));a.S=0},O7=function(a){return!!a.i&&3==a.i.getState()},N7=function(a){if(a.i){var b=a.oa(),c=a.i.Zj||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.Zj=c}},P7=function(a){this.port=this.domain="";
this.i="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.ui(4,a))||"";b&&(this.port=":"+b);this.domain=g.vi(a)||"";a=g.Bb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.yb(a,"10.0")&&(this.u=!1))},Q7=function(a,b){var c=a.i;
a.u&&(c="https://"+a.domain+a.port+a.i);return g.Gi(c+b,{})},R7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.C,d,!0),onError:g.Sa(a.B,e),onTimeout:g.Sa(a.D,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.du(b,a)},DUa=function(){var a=AUa;
BUa();S7.push(a);CUa()},T7=function(a,b){BUa();
var c=EUa(a,String(b));g.Sb(S7)?FUa(c):(CUa(),g.lc(S7,function(d){d(c)}))},BUa=function(){S7||(S7=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",S7,void 0))},FUa=function(a){var b=(U7+1)%50;
U7=b;V7[b]=a;W7||(W7=49==b)},CUa=function(){var a=S7;
if(V7[0]){var b=W7?U7:-1;do{b=(b+1)%50;var c=V7[b];g.lc(a,function(d){d(c)})}while(b!=U7);
V7=Array(50);U7=-1;W7=!1}},EUa=function(a,b){var c=(Date.now()-GUa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},X7=function(a){g.Q.call(this);
this.I=a;this.screens=[]},HUa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},IUa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.ep(a.screens,function(f){return!!Z6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=HUa(a,b[d])||c;return c},JUa=function(a,b){var c=a.screens.length;
a.screens=g.ep(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},Y7=function(a,b,c,d,e){g.Q.call(this);
this.B=a;this.K=b;this.C=c;this.I=d;this.D=e;this.u=0;this.i=null;this.Mb=NaN},$7=function(a){X7.call(this,"LocalScreenService");
this.u=a;this.i=NaN;Z7(this);this.info("Initializing with "+X6(this.screens))},KUa=function(a){if(a.screens.length){var b=g.Qm(a.screens,function(d){return d.id}),c=Q7(a.u,"/pairing/get_lounge_token_batch");
R7(a.u,c,{screen_ids:b.join(",")},(0,g.D)(a.aS,a),(0,g.D)(a.ZR,a))}},Z7=function(a){if(g.O("deprecate_pair_servlet_enabled"))return IUa(a,[]);
var b=BTa(HTa());b=g.ep(b,function(c){return!c.uuid});
return IUa(a,b)},a8=function(a,b){JTa(g.Qm(a.screens,zTa));
b&&ITa()},c8=function(a,b){g.Q.call(this);
this.I=b;b=(b=g.Gy("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.I(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.Rb(b,h)}this.i=c;this.D=a;this.B=this.C=NaN;this.u=null;b8("Initialized with "+g.li(this.i))},d8=function(a,b,c){var d=Q7(a.D,"/pairing/get_screen_availability");
R7(a.D,d,{lounge_token:b.token},(0,g.D)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.D)(function(){c(!1)},a))},e8=function(a,b){a:if(Q6(b)!=Q6(a.i))var c=!1;
else{c=g.Ae(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(b8("Updated online screens: "+g.li(a.i)),a.i=b,a.ea("screenChange"));LUa(a)},f8=function(a){isNaN(a.B)||g.Yt(a.B);
a.B=g.Wt((0,g.D)(a.WF,a),0<a.C&&a.C<g.Ta()?2E4:1E4)},b8=function(a){T7("OnlineScreenService",a)},MUa=function(a){var b={};
g.lc(a.I(),function(c){c.token?b[c.token]=c.id:this.ke("Requesting availability of screen w/o lounge token.")});
return b},LUa=function(a){a=g.Ae(g.te(a.i,function(b){return b}));
g.ic(a);a.length?g.Fy("yt-remote-online-screen-ids",a.join(","),60):g.Hy("yt-remote-online-screen-ids")},g8=function(a,b){b=void 0===b?!1:b;
X7.call(this,"ScreenService");this.C=a;this.K=b;this.i=this.u=null;this.B=[];this.D={};NUa(this)},PUa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.Gh(),l=c?$6(h,c):null;c&&(a.K||l)||(l=$6(h,b));if(l){l.uuid=b;var m=h8(a,l);d8(a.i,m,function(n){e(n?m:null)})}else c?OUa(a,c,(0,g.D)(function(n){var p=h8(this,new U6({name:d,
screenId:c,loungeToken:n,dialId:b||""}));d8(this.i,p,function(q){e(q?p:null)})},a),f):e(null)},QUa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},RUa=function(a,b,c){d8(a.i,b,c)},OUa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.du(Q7(a.C,"/pairing/get_lounge_token_batch"),e)},SUa=function(a){a.screens=a.u.Gh();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+X6(a.screens))},NUa=function(a){i8(a);
a.u=new $7(a.C);a.u.subscribe("screenChange",(0,g.D)(a.jS,a));SUa(a);a.K||(a.B=BTa(g.Gy("yt-remote-automatic-screen-cache")||[]));i8(a);a.info("Initializing automatic screens: "+X6(a.B));a.i=new c8(a.C,(0,g.D)(a.Gh,a,!0));a.i.subscribe("screenChange",(0,g.D)(function(){this.ea("onlineScreenChange")},a))},h8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=$6(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),a.K||TUa(a));i8(a);a.D[b.uuid]=b.id;g.Fy("yt-remote-device-id-map",a.D,31536E3);return b},TUa=function(a){a=g.ep(a.B,function(b){return"shortLived"!=b.idType});
g.Fy("yt-remote-automatic-screen-cache",g.Qm(a,zTa))},i8=function(a){a.D=g.Gy("yt-remote-device-id-map")||{}},j8=function(a,b,c){g.Q.call(this);
this.Ba=c;this.B=a;this.i=b;this.C=null},k8=function(a,b){a.C=b;
a.ea("sessionScreen",a.C)},UUa=function(a,b){a.C&&(a.C.token=b,h8(a.B,a.C));
a.ea("sessionScreen",a.C)},l8=function(a,b){T7(a.Ba,b)},m8=function(a,b,c){j8.call(this,a,b,"CastSession");
var d=this;this.config_=c;this.u=null;this.oa=(0,g.D)(this.rQ,this);this.Aa=(0,g.D)(this.oW,this);this.Z=g.Wt(function(){VUa(d,null)},12E4);
this.K=this.D=this.I=this.S=0;this.xa=!1;this.X="unknown"},n8=function(a,b){g.Yt(a.K);
a.K=0;0==b?WUa(a):a.K=g.Wt(function(){WUa(a)},b)},WUa=function(a){XUa(a,"getLoungeToken");
g.Yt(a.D);a.D=g.Wt(function(){YUa(a,null)},3E4)},XUa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.li(void 0));
var c={};c.type=b;a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ia,(0,g.D)(function(){l8(this,"Failed to send message: "+b+".")},a)):l8(a,"Sending yt message without session: "+g.li(c))},o8=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.vK(b,function(c){k8(a,c)},function(){return a.xg()},5)):a.xg(Error("Waiting for session status timed out."))},$Ua=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new U6(b);ZUa(a,d,function(e){e?(a.xa=!0,h8(a.B,d),k8(a,d),a.X="unknown",n8(a,c)):(g.et(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.xg())},5)},VUa=function(a,b){g.Yt(a.Z);
a.Z=0;b?a.config_.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?$Ua(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.et(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),o8(a,b.screenId))):(g.et(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+
".")),o8(a,b.screenId)):o8(a,b.screenId):a.xg(Error("Waiting for session status timed out."))},YUa=function(a,b){g.Yt(a.D);
a.D=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.X=c,n8(a,3E4)):(UUa(a,b.loungeToken),a.xa=!1,a.X="unknown",n8(a,b.loungeTokenRefreshIntervalMs))},ZUa=function(a,b,c,d){g.Yt(a.I);
a.I=0;RUa(a.B,b,function(e){e||0>d?c(e):a.I=g.Wt(function(){ZUa(a,b,c,d-1)},300)})},aVa=function(a){g.Yt(a.S);
a.S=0;g.Yt(a.I);a.I=0;g.Yt(a.Z);a.Z=0;g.Yt(a.D);a.D=0;g.Yt(a.K);a.K=0},p8=function(a,b,c,d){j8.call(this,a,b,"DialSession");
this.config_=d;this.u=this.S=null;this.Aa="";this.La=c;this.Ka=null;this.Z=g.Ia;this.X=NaN;this.Ha=(0,g.D)(this.sQ,this);this.D=g.Ia;this.K=this.I=0;this.oa=!1;this.xa="unknown"},q8=function(a){var b;
return!!(a.config_.enableDialLoungeToken&&(null==(b=a.u)?0:b.getDialAppInfo))},bVa=function(a){a.D=a.B.fI(a.Aa,a.i.label,a.i.friendlyName,q8(a),function(b,c){a.D=g.Ia;
a.oa=!0;k8(a,b);"shortLived"==b.idType&&0<c&&r8(a,c)},function(b){a.D=g.Ia;
a.xg(b)})},cVa=function(a){var b={};
b.pairingCode=a.Aa;b.theme=a.La;MTa()&&(b.env_useStageMdx=1);return g.Ei(b)},s8=function(a){return new Promise(function(b){a.Aa=Y6();
if(a.Ka){var c=new chrome.cast.DialLaunchResponse(!0,cVa(a));b(c);bVa(a)}else a.Z=function(){g.Yt(a.X);a.Z=function(){};
a.X=NaN;var d=new chrome.cast.DialLaunchResponse(!0,cVa(a));b(d);bVa(a)},a.X=g.Wt(function(){a.Z()},100)})},eVa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new U6(b);return(new Promise(function(e){dVa(a,d,function(f){f?(a.oa=!0,h8(a.B,d),k8(a,d),r8(a,c)):g.et(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):s8(a)})},fVa=function(a,b){var c=a.S.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){PUa(a.B,c,b,d,function(f){f&&f.token&&k8(a,f);e(f)},function(f){l8(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):s8(a)})},dVa=function(a,b,c,d){g.Yt(a.I);
a.I=0;RUa(a.B,b,function(e){e||0>d?c(e):a.I=g.Wt(function(){dVa(a,b,c,d-1)},300)})},r8=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
q8(a)&&(g.Yt(a.K),a.K=0,0==b?gVa(a):a.K=g.Wt(function(){gVa(a)},b))},gVa=function(a){q8(a)&&a.u.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.xa=c,r8(a,3E4)):(a.oa=!1,a.xa="unknown",UUa(a,b.loungeToken),r8(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.xa="noLoungeTokenResponse";r8(a,3E4)})},hVa=function(a){g.Yt(a.I);
a.I=0;g.Yt(a.K);a.K=0;a.D();a.D=function(){};
g.Yt(a.X)},t8=function(a,b){j8.call(this,a,b,"ManualSession");
this.u=g.Wt((0,g.D)(this.Ps,this,null),150)},u8=function(a,b){g.Q.call(this);
this.config_=b;this.u=a;this.S=b.appId||"233637DE";this.C=b.theme||"cl";this.X=b.disableCastApi||!1;this.I=b.forceMirroring||!1;this.i=null;this.K=!1;this.B=[];this.D=(0,g.D)(this.hV,this)},iVa=function(a,b){return b?g.Nb(a.B,function(c){return V6(b,c.label)},a):null},v8=function(a){T7("Controller",a)},AUa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},w8=function(a){return a.K||!!a.B.length||!!a.i},x8=function(a,b,c){b!=a.i&&(g.he(a.i),(a.i=b)?(c?a.ea("yt-remote-cast2-receiver-resumed",
b.i):a.ea("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.D)(a.LM,a,b)),b.subscribe("sessionFailed",function(){return jVa(a,b)}),b.getScreen()?a.ea("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.Ps(null)):a.ea("yt-remote-cast2-session-change",null))},jVa=function(a,b){a.i==b&&a.ea("yt-remote-cast2-session-failed")},kVa=function(a){var b=a.u.eI(),c=a.i&&a.i.i;
a=g.Qm(b,function(d){c&&V6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=iVa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},pVa=function(a,b,c,d){d.disableCastApi?y8("Cannot initialize because disabled by Mdx config."):lVa()?mVa(b,d)&&(z8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?nVa(a,c):(window.__onGCastApiAvailable=function(e,f){e?nVa(a,c):(A8("Failed to load cast API: "+f),B8(!1),z8(!1),g.Hy("yt-remote-cast-available"),g.Hy("yt-remote-cast-receiver"),
oVa(),c(!1))},d.loadCastApiSetupScript?g.Jy("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=g7()&&TTa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?i7():89<=g7()?VTa():(j7(),h7(UTa.map(QTa))))):y8("Cannot initialize because not running Chrome")},oVa=function(){y8("dispose");
var a=C8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);qVa(!1);g.Kv(D8);D8.length=0},E8=function(){return!!g.Gy("yt-remote-cast-installed")},rVa=function(){var a=g.Gy("yt-remote-cast-receiver");
return a?a.friendlyName:null},sVa=function(){y8("clearCurrentReceiver");
g.Hy("yt-remote-cast-receiver")},tVa=function(){return E8()?C8()?C8().getCastSession():(A8("getCastSelector: Cast is not initialized."),null):(A8("getCastSelector: Cast API is not installed!"),null)},G8=function(){E8()?C8()?F8()?(y8("Requesting cast selector."),C8().requestSession()):(y8("Wait for cast API to be ready to request the session."),D8.push(g.Jv("yt-remote-cast2-api-ready",G8))):A8("requestCastSelector: Cast is not initialized."):A8("requestCastSelector: Cast API is not installed!")},H8=
function(a,b){F8()?C8().setConnectedScreenStatus(a,b):A8("setConnectedScreenStatus called before ready.")},lVa=function(){var a=0<=g.Bb.search(/ (CrMo|Chrome|CriOS)\//);
return g.nj||a},uVa=function(a,b){C8().init(a,b)},mVa=function(a,b){var c=!1;
C8()||(a=new u8(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.Fy("yt-remote-cast-available",d);S6("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){y8("onReceiverSelected: "+d.friendlyName);
g.Fy("yt-remote-cast-receiver",d);S6("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){y8("onReceiverResumed: "+d.friendlyName);
g.Fy("yt-remote-cast-receiver",d);S6("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){y8("onSessionChange: "+W6(d));
d||g.Hy("yt-remote-cast-receiver");S6("yt-remote-cast2-session-change",d)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
y8("cloudview.createSingleton_: "+c);return c},C8=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},nVa=function(a,b){B8(!0);
z8(!1);uVa(a,function(c){c?(qVa(!0),g.Lv("yt-remote-cast2-api-ready")):(A8("Failed to initialize cast API."),B8(!1),g.Hy("yt-remote-cast-available"),g.Hy("yt-remote-cast-receiver"),oVa());b(c)})},y8=function(a){T7("cloudview",a)},A8=function(a){T7("cloudview",a)},B8=function(a){y8("setCastInstalled_ "+a);
g.Fy("yt-remote-cast-installed",a)},F8=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},qVa=function(a){y8("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},z8=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},I8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.I=this.K=0;this.trackData=null;this.hasNext=this.Ik=!1;this.S=this.D=this.i=this.C=0;this.B=NaN;this.u=!1;this.reset(a)},J8=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Ik=!1;a.hasNext=!1;a.K=0;a.I=g.Ta();a.C=0;a.i=0;a.D=0;a.S=0;a.B=NaN;a.u=!1},K8=function(a){return a.Dc()?(g.Ta()-a.I)/1E3:0},L8=function(a,b){a.K=b;
a.I=g.Ta()},M8=function(a){switch(a.playerState){case 1:case 1081:return(g.Ta()-a.I)/1E3+a.K;
case -1E3:return 0}return a.K},N8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&J8(a)},O8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Me(a.trackData);b.hasPrevious=a.Ik;b.hasNext=a.hasNext;b.playerTime=a.K;b.playerTimeAt=a.I;b.seekableStart=a.C;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.S;b.liveIngestionTime=a.B;return b},Q8=function(a,b){g.Q.call(this);
this.B=0;this.C=a;this.I=[];this.D=new wUa;this.u=this.i=null;this.X=(0,g.D)(this.OT,this);this.K=(0,g.D)(this.Aw,this);this.S=(0,g.D)(this.NT,this);this.Z=(0,g.D)(this.VT,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.lG,this),vVa(this))):c=3;0!=c&&(b?this.lG(c):g.Wt((0,g.D)(function(){this.lG(c)},this),0));
(a=tVa())&&P8(this,a);this.subscribe("yt-remote-cast2-session-change",this.Z)},R8=function(a){return new I8(a.C.getPlayerContextData())},vVa=function(a){g.lc("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange multiStateLoopEnabled loopModeChange".split(" "),function(b){this.I.push(this.C.subscribe(b,g.Sa(this.fV,b),this))},a)},wVa=function(a){g.lc(a.I,function(b){this.C.unsubscribeByKey(b)},a);
a.I.length=0},S8=function(a){return 1==a.getState()},T8=function(a,b){var c=a.D;
50>c.i.length+c.u.length&&a.D.u.push(b)},V8=function(a,b,c){var d=R8(a);
L8(d,c);-1E3!=d.playerState&&(d.playerState=b);U8(a,d)},W8=function(a,b,c){a.C.sendMessage(b,c)},U8=function(a,b){wVa(a);
a.C.setPlayerContextData(O8(b));vVa(a)},P8=function(a,b){a.u&&(a.u.removeUpdateListener(a.X),a.u.removeMediaListener(a.K),a.Aw(null));
a.u=b;a.u&&(T7("CP","Setting cast session: "+a.u.sessionId),a.u.addUpdateListener(a.X),a.u.addMediaListener(a.K),a.u.media.length&&a.Aw(a.u.media[0]))},xVa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=R8(a);b.contentId!=d.videoId&&T7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;L8(d,a.i.getEstimatedTime());U8(a,d)}else T7("CP","No cast media video. Ignoring state update.")},X8=function(a,b,c){return(0,g.D)(function(d){this.ke("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.ke("Retrying "+b+" using MDx browser channel."),W8(this,b,c))},a)},Y8=function(a,b,c,d){d=void 0===d?!1:d;
g.Q.call(this);this.D=NaN;this.xa=!1;this.S=this.K=this.Z=this.oa=NaN;this.X=[];this.C=this.I=this.B=this.jc=this.i=null;this.Ha=a;this.Ba=d;this.X.push(g.bv(window,"beforeunload",(0,g.D)(this.VR,this)));this.u=[];this.jc=new I8;this.Ka=b.id;this.Aa=b.idType;this.i=yVa(this,c);this.i.subscribe("handlerOpened",this.ST,this);this.i.subscribe("handlerClosed",this.PT,this);this.i.subscribe("handlerError",this.QT,this);this.i.subscribe("handlerMessage",this.RT,this);this.i.ZA(b.token);this.subscribe("remoteQueueChange",
function(){var e=this.jc.videoId;g.Iy()&&g.Fy("yt-remote-session-video-id",e)},this)},zVa=function(a){return g.Nb(a.u,function(b){return"LOUNGE_SCREEN"==b.type})},Z8=function(a){T7("conn",a)},yVa=function(a,b){return new M7(Q7(a.Ha,"/bc"),b,!1,function(){return a.jI()},"shortLived"==a.Aa)},$8=function(a,b){a.ea("proxyStateChange",b)},AVa=function(a){a.D=g.Wt((0,g.D)(function(){Z8("Connecting timeout");
this.Zr(1)},a),2E4)},a9=function(a){g.Yt(a.D);
a.D=NaN},b9=function(a){g.Yt(a.oa);
a.oa=NaN},BVa=function(a){c9(a);
a.Z=g.Wt((0,g.D)(function(){d9(this,"getNowPlaying")},a),2E4)},c9=function(a){g.Yt(a.Z);
a.Z=NaN},DVa=function(a,b){var c=null;
if(b){var d=zVa(a);d&&(c={clientName:d.clientName,deviceMake:d.brand,deviceModel:d.model,osVersion:d.osVersion})}g.Ga("yt.mdx.remote.remoteClient_",c,void 0);b&&(a9(a),b9(a));c=O7(a.i)&&isNaN(a.D);b==c?b&&($8(a,1),d9(a,"getSubtitlesTrack")):b?(a.uK()&&a.jc.reset(),$8(a,1),d9(a,"getNowPlaying"),CVa(a)):a.Zr(1)},EVa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.jc.videoId&&(g.He(b.params)?a.jc.trackData=null:a.jc.trackData=b.params,a.ea("remotePlayerChange"))},FVa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.jc.listId=b.params.listId||a.jc.listId;N8(a.jc,c,d);a.ea("remoteQueueChange")},HVa=function(a,b){b.params=b.params||{};
FVa(a,b);GVa(a,b);a.ea("autoplayDismissed")},GVa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
L8(a.jc,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.jc.playerState&&(c=-1E3);a.jc.playerState=c;c=Number(b.params.loadedTime);a.jc.S=isNaN(c)?0:c;a.jc.Kj(Number(b.params.duration));c=a.jc;var d=Number(b.params.liveIngestionTime);c.B=d;c.u=isNaN(d)?!1:!0;c=a.jc;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.jc.playerState?BVa(a):c9(a);a.ea("remotePlayerChange")},IVa=function(a,b){if(-1E3!=a.jc.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.jc.playerState=c;b=parseInt(b.params.currentTime,10);L8(a.jc,isNaN(b)?0:b);a.ea("remotePlayerChange")}},JVa=function(a,b){var c="true"==b.params.muted;
a.jc.volume=parseInt(b.params.volume,10);a.jc.muted=c;a.ea("remotePlayerChange")},KVa=function(a,b){a.I=b.params.videoId;
a.ea("nowAutoplaying",parseInt(b.params.timeout,10))},LVa=function(a,b){var c="true"==b.params.hasNext;
a.jc.Ik="true"==b.params.hasPrevious;a.jc.hasNext=c;a.ea("previousNextChange")},CVa=function(a){g.Yt(a.S);
a.S=g.Wt((0,g.D)(a.Zr,a,1),864E5)},d9=function(a,b,c){c?Z8("Sending: action="+b+", params="+g.li(c)):Z8("Sending: action="+b);
a.i.sendMessage(b,c)},e9=function(a){X7.call(this,"ScreenServiceProxy");
this.Re=a;this.i=[];this.i.push(this.Re.$_s("screenChange",(0,g.D)(this.wQ,this)));this.i.push(this.Re.$_s("onlineScreenChange",(0,g.D)(this.MU,this)))},PVa=function(a,b){LTa();
if(!f7||!f7.get("yt-remote-disable-remote-module-for-dev")){b=g.N("MDX_CONFIG")||b;DTa();d7();f9||(f9=new P7(b?b.loungeApiHost:void 0),MTa()&&(f9.i="/api/loungedev"));g9||(g9=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",g9,void 0));MVa();var c=h9();if(!c){var d=new g8(f9,b?b.disableAutomaticScreenCache||!1:!1);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=h9();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken,forceMirroring:b.forceMirroring});g.Ga("yt.mdx.remote.enableConnectWithInitialState_",b?b.enableConnectWithInitialState||!1:!1,void 0);pVa(a,d,function(f){f?i9()&&H8(i9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){S6("yt-remote-receiver-availability-change")})},e)}b&&!g.Ha("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),j9("Initializing: "+
g.li(b)),k9.push(g.Jv("yt-remote-cast2-api-ready",function(){S6("yt-remote-api-ready")})),k9.push(g.Jv("yt-remote-cast2-availability-change",function(){S6("yt-remote-receiver-availability-change")})),k9.push(g.Jv("yt-remote-cast2-receiver-selected",function(){l9(null);
S6("yt-remote-auto-connect","cast-selector-receiver")})),k9.push(g.Jv("yt-remote-cast2-receiver-resumed",function(){S6("yt-remote-receiver-resumed","cast-selector-receiver")})),k9.push(g.Jv("yt-remote-cast2-session-change",NVa)),k9.push(g.Jv("yt-remote-connection-change",function(f){f?H8(i9(),"YouTube TV"):m9()||(H8(null,null),sVa())})),k9.push(g.Jv("yt-remote-cast2-session-failed",function(){S6("yt-remote-connection-failed")})),a=n9(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.O("desktop_enable_autoplay")&&
e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),j9(" -- with channel params: "+g.li(a)),a?(g.Fy("yt-remote-session-app",a.app),g.Fy("yt-remote-session-name",a.name)):(g.Hy("yt-remote-session-app"),g.Hy("yt-remote-session-name")),g.Ga("yt.mdx.remote.channelParams_",a,void 0),c.start(),i9()||OVa())}},QVa=function(){var a=h9().Re.$_gos();
var b=o9();b&&p9()&&(Z6(a,b)||a.push(b));return CTa(a)},q9=function(){var a=RVa();
!a&&E8()&&rVa()&&(a={key:"cast-selector-receiver",name:rVa()});return a},RVa=function(){var a=QVa(),b=o9();
b||(b=m9());return g.Nb(a,function(c){return b&&V6(b,c.key)?!0:!1})},o9=function(){var a=i9();
if(!a)return null;var b=h9().Gh();return $6(b,a)},NVa=function(a){j9("remote.onCastSessionChange_: "+W6(a));
if(a){var b=o9();if(b&&b.id==a.id){if(H8(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))r9&&(r9.token=a),(b=p9())&&b.ZA(a)}else b&&s9(),t9(a,1)}else p9()&&s9()},s9=function(){F8()?C8().stopSession():A8("stopSession called before API ready.");
var a=p9();a&&(a.disconnect(1),u9(null))},v9=function(){var a=p9();
return!!a&&3!=a.getProxyState()},j9=function(a){T7("remote",a)},h9=function(){if(!w9){var a=g.Ha("yt.mdx.remote.screenService_");
w9=a?new e9(a):null}return w9},i9=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},SVa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},TVa=function(){return g.Ha("yt.mdx.remote.connectData_")},l9=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},p9=function(){return g.Ha("yt.mdx.remote.connection_")},u9=function(a){var b=p9();
l9(null);a||SVa("");g.Ga("yt.mdx.remote.connection_",a,void 0);g9&&(g.lc(g9,function(c){c(a)}),g9.length=0);
b&&!a?S6("yt-remote-connection-change",!1):!b&&a&&S6("yt-remote-connection-change",!0)},m9=function(){var a=g.Iy();
if(!a)return null;var b=h9();if(!b)return null;b=b.Gh();return $6(b,a)},t9=function(a,b){i9();
o9()&&o9();if(x9)r9=a;else{SVa(a.id);var c=g.Ha("yt.mdx.remote.enableConnectWithInitialState_")||!1;a=new Y8(f9,a,n9(),c);a.connect(b,TVa());a.subscribe("beforeDisconnect",function(d){S6("yt-remote-before-disconnect",d)});
a.subscribe("beforeDispose",function(){p9()&&(p9(),u9(null))});
a.subscribe("browserChannelAuthError",function(){var d=o9();d&&"shortLived"==d.idType&&(F8()?C8().handleBrowserChannelAuthError():A8("refreshLoungeToken called before API ready."))});
u9(a)}},OVa=function(){var a=m9();
a?(j9("Resume connection to: "+W6(a)),t9(a,0)):(e7(),sVa(),j9("Skipping connecting because no session screen found."))},MVa=function(){var a=n9();
if(g.He(a)){a=c7();var b=g.Gy("yt-remote-session-name")||"",c=g.Gy("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},n9=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},y9=function(a,b,c){g.E.call(this);
var d=this;this.u=a;this.J=b;this.Tb=c;this.events=new g.aD(this);this.Z=this.events.T(this.J,"onVolumeChange",function(e){UVa(d,e)});
this.D=!1;this.I=new g.GJ(64);this.i=new g.I(this.QN,500,this);this.B=new g.I(this.RN,1E3,this);this.S=new k7(this.DX,0,this);this.C={};this.X=new g.I(this.zO,1E3,this);this.K=new l7(this.seekTo,1E3,this);this.oa=g.Ia;g.H(this,this.events);this.events.T(b,"onCaptionsTrackListChanged",this.xU);this.events.T(b,"captionschanged",this.KT);this.events.T(b,"captionssettingschanged",this.XN);this.events.T(b,"videoplayerreset",this.sA);this.events.T(b,"mdxautoplaycancel",function(){d.Tb.RJ()});
a=this.Tb;a.isDisposed();a.subscribe("proxyStateChange",this.HM,this);a.subscribe("remotePlayerChange",this.Fw,this);a.subscribe("remoteQueueChange",this.sA,this);a.subscribe("previousNextChange",this.EM,this);a.subscribe("nowAutoplaying",this.yM,this);a.subscribe("autoplayDismissed",this.bM,this);g.H(this,this.i);g.H(this,this.B);g.H(this,this.S);g.H(this,this.X);g.H(this,this.K);this.XN();this.sA();this.Fw()},UVa=function(a,b){if(z9(a)){a.Tb.unsubscribe("remotePlayerChange",a.Fw,a);
var c=Math.round(b.volume);b=!!b.muted;var d=R8(a.Tb);if(c!==d.volume||b!==d.muted)a.Tb.setVolume(c,b),a.X.start();a.Tb.subscribe("remotePlayerChange",a.Fw,a)}},VVa=function(a){a.Xb(0);
a.i.stop();a.Ub(new g.GJ(64))},A9=function(a,b){if(z9(a)&&!a.D){var c=null;
b&&(c={style:a.J.getSubtitlesUserSettings()},g.Oe(c,b));a.Tb.iI(a.J.getVideoData(1).videoId,c);a.C=R8(a.Tb).trackData}},B9=function(a,b){var c=a.J.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.J.getVideoData(1);a.Tb.playVideo(c.videoId,b,d,e,c.playerParams,c.Za,sTa(c));a.Ub(new g.GJ(1))},WVa=function(a,b){if(b){var c=a.J.getOption("captions","tracklist",{SK:1});
c&&c.length?(a.J.setOption("captions","track",b),a.D=!1):(a.J.loadModule("captions"),a.D=!0)}else a.J.setOption("captions","track",{})},z9=function(a){return R8(a.Tb).videoId===a.J.getVideoData(1).videoId},C9=function(){g.W.call(this,{G:"div",
L:"ytp-mdx-popup-dialog",W:{role:"dialog"},U:[{G:"div",L:"ytp-mdx-popup-dialog-inner-content",U:[{G:"div",L:"ytp-mdx-popup-title",ya:"You're signed out"},{G:"div",L:"ytp-mdx-popup-description",ya:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{G:"div",L:"ytp-mdx-privacy-popup-buttons",U:[{G:"button",Ga:["ytp-button","ytp-mdx-privacy-popup-cancel"],ya:"Cancel"},{G:"button",Ga:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],ya:"Confirm"}]}]}]});this.i=new g.lL(this,250);this.cancelButton=this.Fa("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Fa("ytp-mdx-privacy-popup-confirm");g.H(this,this.i);this.T(this.cancelButton,"click",this.u);this.T(this.confirmButton,"click",this.B)},D9=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",U:[{G:"div",L:"ytp-remote-display-status",U:[{G:"div",L:"ytp-remote-display-status-icon",U:[g.hua()]},{G:"div",L:"ytp-remote-display-status-text",ya:"{{statustext}}"}]}]});this.api=a;this.i=new g.lL(this,250);g.H(this,this.i);this.T(a,"presentingplayerstatechange",this.onStateChange);XVa(this,a.zb())},XVa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.T(b,128)?g.dI("Error on $RECEIVER_NAME",c):b.Dc()||g.T(b,4)?g.dI("Playing on $RECEIVER_NAME",c):g.dI("Connected to $RECEIVER_NAME",c);a.Ra("statustext",b);a.i.show()}else a.i.hide()},E9=function(a,b){g.FP.call(this,"Play on",0,a,b);
this.J=a;this.Bo={};this.T(a,"onMdxReceiversChange",this.D);this.T(a,"presentingplayerstatechange",this.D);this.D()},F9=function(a){g.PM.call(this,a);
this.Pk={key:Y6(),name:"This computer"};this.di=null;this.subscriptions=[];this.KF=this.Tb=null;this.Bo=[this.Pk];this.cn=this.Pk;this.zd=new g.GJ(64);this.tL=0;this.vf=-1;this.Ow=!1;this.Mw=this.nt=null;if(!g.LE(this.player.V())&&!g.ME(this.player.V())){a=this.player;var b=g.sM(a);b&&(b=b.En())&&(b=new E9(a,b),g.H(this,b));b=new D9(a);g.H(this,b);g.CM(a,b.element,4);this.nt=new C9;g.H(this,this.nt);g.CM(a,this.nt.element,4);this.Ow=!!m9()}},G9=function(a){a.Mw&&(a.player.removeEventListener("presentingplayerstatechange",
a.Mw),a.Mw=null)},YVa=function(a,b,c){a.zd=c;
a.player.ea("presentingplayerstatechange",new g.NH(c,b))},H9=function(a,b){if(b.key!==a.cn.key)if(b.key===a.Pk.key)s9();
else{var c;(c=!a.player.V().N("mdx_enable_privacy_disclosure_ui"))||(c=((c=g.N("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.N("SESSION_INDEX")&&!g.N("LOGGED_IN")))||a.Ow||!a.nt);(c?0:g.bF(a.player.V())||g.eF(a.player.V()))&&ZVa(a);a.cn=b;if(!a.player.V().N("disable_mdx_connection_in_mdx_module_for_music_web")||!g.ME(a.player.V())){var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&a.player.V().N("should_clear_video_data_on_player_cued_unstarted"))a=
null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=g.JM(f,l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Za,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=sTa(c))&&(a.locationInfo=c)}j9("Connecting to: "+g.li(b));"cast-selector-receiver"==b.key?(l9(a||null),b=a||null,F8()?C8().setLaunchParams(b):A8("setLaunchParams called before ready.")):!a&&v9()&&
i9()==b.key?S6("yt-remote-connection-change",!0):(s9(),l9(a||null),a=h9().Gh(),(b=$6(a,b.key))&&t9(b,1))}}},ZVa=function(a){a.player.zb().Dc()?a.player.pauseVideo():(a.Mw=function(b){!a.Ow&&g.PH(b,8)&&(a.player.pauseVideo(),G9(a))},a.player.addEventListener("presentingplayerstatechange",a.Mw));
a.nt&&a.nt.yd();p9()||(x9=!0)},aUa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},x7={"'":"\\'"},yTa={YY:"atp",w$:"ska",h9:"que",Y6:"mus",v$:"sus",U2:"dsp",D9:"seq",B6:"mic",K1:"dpa",nZ:"cds",W6:"mlm",I1:"dsdtr"},f7,b7="",STa=NTa("loadCastFramework")||NTa("loadCastApplicationFramework"),UTa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ua(k7,g.E);g.k=k7.prototype;g.k.kQ=function(a){this.C=arguments;this.i=!1;this.Mb?this.B=g.Ta()+this.Tf:this.Mb=g.Ih(this.D,this.Tf)};
g.k.stop=function(){this.Mb&&(g.B.clearTimeout(this.Mb),this.Mb=null);this.B=null;this.i=!1;this.C=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.i&&(this.i=!1,this.I.apply(null,this.C)))};
g.k.va=function(){this.stop();k7.je.va.call(this)};
g.k.lQ=function(){this.Mb&&(g.B.clearTimeout(this.Mb),this.Mb=null);this.B?(this.Mb=g.Ih(this.D,this.B-g.Ta()),this.B=null):this.u?this.i=!0:(this.i=!1,this.I.apply(null,this.C))};g.v(l7,g.E);g.k=l7.prototype;g.k.dI=function(a){this.B=arguments;this.Mb||this.u?this.i=!0:m7(this)};
g.k.stop=function(){this.Mb&&(g.B.clearTimeout(this.Mb),this.Mb=null,this.i=!1,this.B=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.i||this.Mb||(this.i=!1,m7(this))};
g.k.va=function(){g.E.prototype.va.call(this);this.stop()};n7.prototype.stringify=function(a){return g.B.JSON.stringify(a,void 0)};
n7.prototype.parse=function(a){return g.B.JSON.parse(a,void 0)};var p7=new g.ff;g.v(WTa,g.ke);g.k=r7.prototype;g.k.Wo=null;g.k.Fm=!1;g.k.Vt=null;g.k.dH=null;g.k.wt=null;g.k.Kt=null;g.k.Um=null;g.k.Eo=null;g.k.wq=null;g.k.Kf=null;g.k.zB=0;g.k.Pj=null;g.k.xB=null;g.k.Om=null;g.k.Cu=-1;g.k.FN=!0;g.k.np=!1;g.k.nC=0;g.k.NA=null;var ZTa={},u7={};g.k=r7.prototype;g.k.setTimeout=function(a){this.u=a};
g.k.mQ=function(a){a=a.target;var b=this.NA;b&&3==g.Ti(a)?b.dI():this.HO(a)};
g.k.HO=function(a){try{if(a==this.Kf)a:{var b=g.Ti(this.Kf),c=this.Kf.u,d=this.Kf.getStatus();if(g.Dc&&!g.vc(10)||g.Jg&&!g.uc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Yi(this.Kf))break a;this.np||4!=b||7==c||(8==c||0>=d?this.i.Bj(3):this.i.Bj(2));y7(this);var e=this.Kf.getStatus();this.Cu=e;var f=g.Yi(this.Kf);if(this.Fm=200==e){4==b&&v7(this);if(this.D){for(a=!0;!this.np&&this.zB<f.length;){var h=$Ta(this,f);if(h==u7){4==b&&(this.Om=4,q7(15),a=!1);break}else if(h==ZTa){this.Om=4;q7(16);a=!1;
break}else z7(this,h)}4==b&&0==f.length&&(this.Om=1,q7(17),a=!1);this.Fm=this.Fm&&a;a||(v7(this),w7(this))}else z7(this,f);this.Fm&&!this.np&&(4==b?this.i.Yx(this):(this.Fm=!1,t7(this)))}else 400==e&&0<f.indexOf("Unknown SID")?(this.Om=3,q7(13)):(this.Om=0,q7(14)),v7(this),w7(this)}}catch(l){this.Kf&&g.Yi(this.Kf)}finally{}};
g.k.dW=function(a){o7((0,g.D)(this.cW,this,a),0)};
g.k.cW=function(a){this.np||(y7(this),z7(this,a),t7(this))};
g.k.QM=function(a){o7((0,g.D)(this.bW,this,a),0)};
g.k.bW=function(a){this.np||(v7(this),this.Fm=a,this.i.Yx(this),this.i.Bj(4))};
g.k.cancel=function(){this.np=!0;v7(this)};
g.k.kW=function(){this.Vt=null;var a=Date.now();0<=a-this.dH?(2!=this.Kt&&this.i.Bj(3),v7(this),this.Om=2,q7(18),w7(this)):cUa(this,this.dH-a)};
g.k.getLastError=function(){return this.Om};g.k=fUa.prototype;g.k.oC=null;g.k.ph=null;g.k.OA=!1;g.k.SN=null;g.k.Ry=null;g.k.JE=null;g.k.pC=null;g.k.Yh=null;g.k.ql=-1;g.k.Du=null;g.k.Tu=null;g.k.connect=function(a){this.pC=a;a=B7(this.i,null,this.pC);q7(3);this.SN=Date.now();var b=this.i.S;null!=b?(this.Du=b[0],(this.Tu=b[1])?(this.Yh=1,gUa(this)):(this.Yh=2,D7(this))):(P6(a,"MODE","init"),this.ph=new r7(this,void 0,void 0,void 0),this.ph.Wo=this.oC,s7(this.ph,a,!1,null,!0),this.Yh=0)};
g.k.dR=function(a){if(a)this.Yh=2,D7(this);else{q7(4);var b=this.i;b.bk=b.Ym.ql;K7(b,9)}a&&this.Bj(2)};
g.k.rD=function(a){return this.i.rD(a)};
g.k.abort=function(){this.ph&&(this.ph.cancel(),this.ph=null);this.ql=-1};
g.k.rf=function(){return!1};
g.k.IM=function(a,b){this.ql=a.Cu;if(0==this.Yh)if(b){try{var c=this.u.parse(b)}catch(d){a=this.i;a.bk=this.ql;K7(a,2);return}this.Du=c[0];this.Tu=c[1]}else a=this.i,a.bk=this.ql,K7(a,2);else if(2==this.Yh)if(this.OA)q7(7),this.JE=Date.now();else if("11111"==b){if(q7(6),this.OA=!0,this.Ry=Date.now(),a=this.Ry-this.SN,!g.Dc||g.vc(10)||500>a)this.ql=200,this.ph.cancel(),q7(12),C7(this.i,this,!0)}else q7(8),this.Ry=this.JE=Date.now(),this.OA=!1};
g.k.Yx=function(){this.ql=this.ph.Cu;if(this.ph.Fm)0==this.Yh?this.Tu?(this.Yh=1,gUa(this)):(this.Yh=2,D7(this)):2==this.Yh&&((!g.Dc||g.vc(10)?!this.OA:200>this.JE-this.Ry)?(q7(11),C7(this.i,this,!1)):(q7(12),C7(this.i,this,!0)));else{0==this.Yh?q7(9):2==this.Yh&&q7(10);var a=this.i;this.ph.getLastError();a.bk=this.ql;K7(a,2)}};
g.k.nx=function(){return this.i.nx()};
g.k.isActive=function(){return this.i.isActive()};
g.k.Bj=function(a){this.i.Bj(a)};g.k=E7.prototype;g.k.Zj=null;g.k.yv=null;g.k.Tg=null;g.k.Ie=null;g.k.qC=null;g.k.Sy=null;g.k.fJ=null;g.k.Zx=null;g.k.pw=0;g.k.fT=0;g.k.Lf=null;g.k.vn=null;g.k.El=null;g.k.zp=null;g.k.Ym=null;g.k.vB=null;g.k.Os=-1;g.k.sL=-1;g.k.bk=-1;g.k.ls=0;g.k.Lr=0;g.k.pp=8;g.Ua(iUa,g.ke);g.Ua(jUa,g.ke);g.k=E7.prototype;g.k.connect=function(a,b,c,d,e){q7(0);this.qC=b;this.yv=c||{};d&&void 0!==e&&(this.yv.OSID=d,this.yv.OAID=e);this.I?(o7((0,g.D)(this.BJ,this,a),100),nUa(this)):this.BJ(a)};
g.k.BJ=function(a){this.Ym=new fUa(this);this.Ym.oC=this.Zj;this.Ym.u=this.D;this.Ym.connect(a)};
g.k.rf=function(){return 0==this.i};
g.k.getState=function(){return this.i};
g.k.OM=function(a){this.vn=null;rUa(this,a)};
g.k.MM=function(){this.El=null;this.Ie=new r7(this,this.B,"rpc",this.K);this.Ie.Wo=this.Zj;this.Ie.nC=0;var a=this.fJ.clone();g.Lk(a,"RID","rpc");g.Lk(a,"SID",this.B);g.Lk(a,"CI",this.vB?"0":"1");g.Lk(a,"AID",this.Os);F7(this,a);if(!g.Dc||g.vc(10))g.Lk(a,"TYPE","xmlhttp"),s7(this.Ie,a,!0,this.Zx,!1);else{g.Lk(a,"TYPE","html");var b=this.Ie,c=!!this.Zx;b.Kt=3;b.Um=O6(a.clone());bUa(b,c)}};
g.k.IM=function(a,b){if(0!=this.i&&(this.Ie==a||this.Tg==a))if(this.bk=a.Cu,this.Tg==a&&3==this.i)if(7<this.pp){try{var c=this.D.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.El){if(this.Ie)if(this.Ie.wt+3E3<this.Tg.wt)H7(this),this.Ie.cancel(),this.Ie=null;else break a;J7(this);q7(19)}}else this.sL=a[1],0<this.sL-this.Os&&37500>a[2]&&this.vB&&0==this.Lr&&!this.zp&&(this.zp=o7((0,g.D)(this.HT,this),6E3));else K7(this,11)}else null!=b&&K7(this,11);else if(this.Ie==
a&&H7(this),!g.kb(b))for(a=this.D.parse(b),b=0;b<a.length;b++)c=a[b],this.Os=c[0],c=c[1],2==this.i?"c"==c[0]?(this.B=c[1],this.Zx=c[2],c=c[3],null!=c?this.pp=c:this.pp=6,this.i=3,this.Lf&&this.Lf.xJ(),this.fJ=B7(this,this.nx()?this.Zx:null,this.qC),sUa(this)):"stop"==c[0]&&K7(this,7):3==this.i&&("stop"==c[0]?K7(this,7):"noop"!=c[0]&&this.Lf&&this.Lf.wJ(c),this.Lr=0)};
g.k.HT=function(){null!=this.zp&&(this.zp=null,this.Ie.cancel(),this.Ie=null,J7(this),q7(20))};
g.k.Yx=function(a){if(this.Ie==a){H7(this);this.Ie=null;var b=2}else if(this.Tg==a)this.Tg=null,b=1;else return;this.bk=a.Cu;if(0!=this.i)if(a.Fm)if(1==b){b=Date.now()-a.wt;var c=p7;c.dispatchEvent(new iUa(c,a.wq?a.wq.length:0,b,this.ls));G7(this);this.C.length=0}else sUa(this);else{c=a.getLastError();var d;if(!(d=3==c||7==c||0==c&&0<this.bk)){if(d=1==b)this.Tg||this.vn||1==this.i||2<=this.ls?d=!1:(this.vn=o7((0,g.D)(this.OM,this,a),tUa(this,this.ls)),this.ls++,d=!0);d=!(d||2==b&&J7(this))}if(d)switch(c){case 1:K7(this,
5);break;case 4:K7(this,10);break;case 3:K7(this,6);break;case 7:K7(this,12);break;default:K7(this,2)}}};
g.k.DR=function(a){if(!g.Rb(arguments,this.i))throw Error("Unexpected channel state: "+this.i);};
g.k.nX=function(a){a?q7(2):(q7(1),uUa(this,8))};
g.k.rD=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Ni;a.S=!1;return a};
g.k.isActive=function(){return!!this.Lf&&this.Lf.isActive(this)};
g.k.Bj=function(a){var b=p7;b.dispatchEvent(new jUa(b,a))};
g.k.nx=function(){return!(!g.Dc||g.vc(10))};
g.k=vUa.prototype;g.k.xJ=function(){};
g.k.wJ=function(){};
g.k.vJ=function(){};
g.k.eD=function(){};
g.k.iK=function(){return{}};
g.k.isActive=function(){return!0};g.k=wUa.prototype;g.k.isEmpty=function(){return 0===this.i.length&&0===this.u.length};
g.k.clear=function(){this.i=[];this.u=[]};
g.k.contains=function(a){return g.Rb(this.i,a)||g.Rb(this.u,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.ANa)(b,a);0<=c?(g.Ub(b,c),b=!0):b=!1;return b||g.Vb(this.u,a)};
g.k.Np=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ua(L7,g.E);g.k=L7.prototype;g.k.UV=function(){this.Tf=Math.min(3E5,2*this.Tf);this.B();this.u&&this.start()};
g.k.start=function(){var a=this.Tf+15E3*Math.random();g.fr(this.i,a);this.u=Date.now()+a};
g.k.stop=function(){this.i.stop();this.u=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Tf=5E3};g.Ua(M7,vUa);g.k=M7.prototype;g.k.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.k.ag=function(a){return this.B.ag(a)};
g.k.ea=function(a,b){return this.B.ea.apply(this.B,arguments)};
g.k.dispose=function(){this.Z||(this.Z=!0,g.he(this.B),zUa(this),g.he(this.u),this.u=null,this.oa=function(){return""})};
g.k.isDisposed=function(){return this.Z};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.X="";this.u.stop();this.D=a||null;this.C=b||0;a=this.xa+"/test";b=this.xa+"/bind";var d=new E7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.Aa),e=this.i;e&&(e.Lf=null);d.Lf=this;this.i=d;N7(this);if(this.i){d=g.N("ID_TOKEN");var f=this.i.Zj||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.Zj=f}e?(3!=e.getState()&&0==pUa(e)||e.getState(),this.i.connect(a,b,this.I,e.B,e.Os)):c?this.i.connect(a,
b,this.I,c.sessionId,c.arrayId):this.i.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.Oe(a,b);this.u.isActive()||2==(this.i?this.i.getState():0)?this.K.push(a):O7(this)&&(N7(this),oUa(this.i,a))};
g.k.xJ=function(){this.u.reset();this.D=null;this.C=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)oUa(this.i,a[b])}this.ea("handlerOpened")};
g.k.vJ=function(a){var b=2==a&&401==this.i.bk;4==a||b||this.u.start();this.ea("handlerError",a,b)};
g.k.eD=function(a){if(!this.u.isActive())this.ea("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.iK=function(){var a={v:2};this.X&&(a.gsessionid=this.X);0!=this.C&&(a.ui=""+this.C);0!=this.S&&(a.ui=""+this.S);this.D&&g.Oe(a,this.D);return a};
g.k.wJ=function(a){"S"==a[0]?this.X=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),mUa(this.i)):this.ea("handlerMessage",new xUa(a[0],a[1]))};
g.k.ZA=function(a){(this.I.loungeIdToken=a)||this.u.stop();if(this.Ba&&this.i){var b=this.i.Zj||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.Zj=b}};
g.k.RW=function(){this.u.isActive();0==pUa(this.i)&&this.connect(this.D,this.C)};P7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
P7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
P7.prototype.D=function(a){a(Error("request timed out"))};var GUa=Date.now(),S7=null,V7=Array(50),U7=-1,W7=!1;g.Ua(X7,g.Q);X7.prototype.Gh=function(){return this.screens};
X7.prototype.contains=function(a){return!!Z6(this.screens,a)};
X7.prototype.get=function(a){return a?$6(this.screens,a):null};
X7.prototype.info=function(a){T7(this.I,a)};g.v(Y7,g.Q);g.k=Y7.prototype;g.k.start=function(){!this.i&&isNaN(this.Mb)&&this.aN()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.Mb)||(g.Yt(this.Mb),this.Mb=NaN)};
g.k.va=function(){this.stop();g.Q.prototype.va.call(this)};
g.k.aN=function(){this.Mb=NaN;this.i=g.du(Q7(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.K},timeout:5E3,onSuccess:(0,g.D)(this.oQ,this),onError:(0,g.D)(this.nQ,this),onTimeout:(0,g.D)(this.pQ,this)})};
g.k.oQ=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.C;a.name=this.I;b=-1;this.D&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.ea("pairingComplete",new U6(a),b)};
g.k.nQ=function(a){this.i=null;a.status&&404==a.status?this.u>=$Va.length?this.ea("pairingFailed",Error("DIAL polling timed out")):(a=$Va[this.u],this.Mb=g.Wt((0,g.D)(this.aN,this),a),this.u++):this.ea("pairingFailed",Error("Server error "+a.status))};
g.k.pQ=function(){this.i=null;this.ea("pairingFailed",Error("Server not responding"))};
var $Va=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ua($7,X7);g.k=$7.prototype;g.k.start=function(){Z7(this)&&this.ea("screenChange");!g.Gy("yt-remote-lounge-token-expiration")&&KUa(this);g.Yt(this.i);this.i=g.Wt((0,g.D)(this.start,this),1E4)};
g.k.add=function(a,b){Z7(this);HUa(this,a);a8(this,!1);this.ea("screenChange");b(a);a.token||KUa(this)};
g.k.remove=function(a,b){var c=Z7(this);JUa(this,a)&&(a8(this,!1),c=!0);b(a);c&&this.ea("screenChange")};
g.k.tB=function(a,b,c,d){var e=Z7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,a8(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.ea("screenChange")};
g.k.va=function(){g.Yt(this.i);$7.je.va.call(this)};
g.k.aS=function(a){Z7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}a8(this,!b);b&&T7(this.I,"Missed "+b+" lounge tokens.")};
g.k.ZR=function(a){T7(this.I,"Requesting lounge tokens failed: "+a)};g.v(c8,g.Q);g.k=c8.prototype;g.k.start=function(){var a=parseInt(g.Gy("yt-remote-fast-check-period")||"0",10);(this.C=g.Ta()-144E5<a?0:a)?f8(this):(this.C=g.Ta()+3E5,g.Fy("yt-remote-fast-check-period",this.C),this.WF())};
g.k.isEmpty=function(){return g.He(this.i)};
g.k.update=function(){b8("Updating availability on schedule.");var a=this.I(),b=g.te(this.i,function(c,d){return c&&!!$6(a,d)},this);
e8(this,b)};
g.k.va=function(){g.Yt(this.B);this.B=NaN;this.u&&(this.u.abort(),this.u=null);g.Q.prototype.va.call(this)};
g.k.WF=function(){g.Yt(this.B);this.B=NaN;this.u&&this.u.abort();var a=MUa(this);if(Q6(a)){var b=Q7(this.D,"/pairing/get_screen_availability");this.u=R7(this.D,b,{lounge_token:g.Ae(a).join(",")},(0,g.D)(this.AV,this,a),(0,g.D)(this.zV,this))}else e8(this,{}),f8(this)};
g.k.AV=function(a,b){this.u=null;var c=g.Ae(MUa(this));if(g.jc(c,g.Ae(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;e8(this,c);f8(this)}else this.ke("Changing Screen set during request."),this.WF()};
g.k.zV=function(a){this.ke("Screen availability failed: "+a);this.u=null;f8(this)};
g.k.ke=function(a){T7("OnlineScreenService",a)};g.Ua(g8,X7);g.k=g8.prototype;g.k.start=function(){this.u.start();this.i.start();this.screens.length&&(this.ea("screenChange"),this.i.isEmpty()||this.ea("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.i.update()};
g.k.tB=function(a,b,c,d){this.u.contains(a)?this.u.tB(a,b,c,d):(a="Updating name of unknown screen: "+a.name,T7(this.I,a),d(Error(a)))};
g.k.Gh=function(a){return a?this.screens:g.Xb(this.screens,g.ep(this.B,function(b){return!this.contains(b)},this))};
g.k.eI=function(){return g.ep(this.Gh(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.fI=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new Y7(this.C,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.he(l);e(h8(h,m),n)});
l.subscribe("pairingFailed",function(m){g.he(l);f(m)});
l.start();return(0,g.D)(l.stop,l)};
g.k.qQ=function(a,b,c,d){g.du(Q7(this.C,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.D)(function(e,f){e=new U6(f.screen||{});if(!e.name||QUa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);QUa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(h8(this,e))},this),
onError:(0,g.D)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.D)(function(){d(Error("pairing request timed out."))},this)})};
g.k.va=function(){g.he(this.u);g.he(this.i);g8.je.va.call(this)};
g.k.jS=function(){SUa(this);this.ea("screenChange");this.i.update()};
g8.prototype.dispose=g8.prototype.dispose;g.Ua(j8,g.Q);g.k=j8.prototype;g.k.getScreen=function(){return this.C};
g.k.xg=function(a){this.isDisposed()||(a&&(l8(this,""+a),this.ea("sessionFailed")),this.C=null,this.ea("sessionScreen",null))};
g.k.info=function(a){T7(this.Ba,a)};
g.k.gI=function(){return null};
g.k.kG=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.D)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.D)(function(){l8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.va=function(){this.kG("");j8.je.va.call(this)};g.v(m8,j8);g.k=m8.prototype;g.k.jG=function(a){if(this.u){if(this.u==a)return;l8(this,"Overriding cast session with new session object");aVa(this);this.xa=!1;this.X="unknown";this.u.removeUpdateListener(this.oa);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa)}this.u=a;this.u.addUpdateListener(this.oa);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa);XUa(this,"getMdxSessionStatus")};
g.k.Ps=function(a){this.info("launchWithParams no-op for Cast: "+g.li(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.D)(function(){this.xg()},this),(0,g.D)(function(){this.xg(Error("Failed to stop receiver app."))},this)):this.xg(Error("Stopping cast device without session."))};
g.k.kG=function(){};
g.k.va=function(){this.info("disposeInternal");aVa(this);this.u&&(this.u.removeUpdateListener(this.oa),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa));this.u=null;j8.prototype.va.call(this)};
g.k.oW=function(a,b){if(!this.isDisposed())if(b)if(b=R6(b),g.Ma(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.li(b)),a){case "mdxSessionStatus":VUa(this,b);break;case "loungeToken":YUa(this,b);break;default:l8(this,"Unknown youtube message: "+a)}else l8(this,"Unable to parse message.");else l8(this,"No data in message.")};
g.k.vK=function(a,b,c,d){g.Yt(this.S);this.S=0;PUa(this.B,this.i.label,a,this.i.friendlyName,(0,g.D)(function(e){e?b(e):0<=d?(l8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.S=g.Wt((0,g.D)(this.vK,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.gI=function(){return this.u};
g.k.rQ=function(a){this.isDisposed()||a||(l8(this,"Cast session died."),this.xg())};g.v(p8,j8);g.k=p8.prototype;g.k.jG=function(a){this.u=a;this.u.addUpdateListener(this.Ha)};
g.k.Ps=function(a){this.Ka=a;this.Z()};
g.k.stop=function(){hVa(this);this.u?this.u.stop((0,g.D)(this.xg,this,null),(0,g.D)(this.xg,this,"Failed to stop DIAL device.")):this.xg()};
g.k.va=function(){hVa(this);this.u&&this.u.removeUpdateListener(this.Ha);this.u=null;j8.prototype.va.call(this)};
g.k.sQ=function(a){this.isDisposed()||a||(l8(this,"DIAL session died."),this.D(),this.D=g.Ia,this.xg())};g.v(t8,j8);t8.prototype.stop=function(){this.xg()};
t8.prototype.jG=function(){};
t8.prototype.Ps=function(){g.Yt(this.u);this.u=NaN;var a=$6(this.B.Gh(),this.i.label);a?k8(this,a):this.xg(Error("No such screen"))};
t8.prototype.va=function(){g.Yt(this.u);this.u=NaN;j8.prototype.va.call(this)};g.v(u8,g.Q);g.k=u8.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.S,[chrome.cast.Capability.AUDIO_OUT]);this.X||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a||this.I?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.D)(this.kV,this);c=new chrome.cast.ApiConfig(c,(0,g.D)(this.JM,this),e,d,a);c.customDialLaunchCallback=(0,g.D)(this.fU,this);
chrome.cast.initialize(c,(0,g.D)(function(){this.isDisposed()||(chrome.cast.addReceiverActionListener(this.D),DUa(),this.u.subscribe("onlineScreenChange",(0,g.D)(this.hI,this)),this.B=kVa(this),chrome.cast.setCustomReceivers(this.B,g.Ia,(0,g.D)(function(f){this.ke("Failed to set initial custom receivers: "+g.li(f))},this)),this.ea("yt-remote-cast2-availability-change",w8(this)),b(!0))},this),(0,g.D)(function(f){this.ke("Failed to initialize API: "+g.li(f));
b(!1)},this))};
g.k.WW=function(a,b){v8("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)v8("Unsetting old screen status: "+this.i.i.friendlyName),x8(this,null)}if(a&&b){if(!this.i){c=$6(this.u.Gh(),a);if(!c){v8("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){v8("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=iVa(this,c);a||(v8("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.B.push(a),chrome.cast.setCustomReceivers(this.B,g.Ia,(0,g.D)(function(d){this.ke("Failed to set initial custom receivers: "+g.li(d))},this)));
v8("setConnectedScreenStatus: new active receiver: "+a.friendlyName);x8(this,new t8(this.u,a),!0)}this.i.kG(b)}else v8("setConnectedScreenStatus: no screen.")};
g.k.XW=function(a){this.isDisposed()?this.ke("Setting connection data on disposed cast v2"):this.i?this.i.Ps(a):this.ke("Setting connection data without a session")};
g.k.uQ=function(){this.isDisposed()?this.ke("Stopping session on disposed cast v2"):this.i?(this.i.stop(),x8(this,null)):v8("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.D)(this.JM,this),(0,g.D)(this.EV,this))};
g.k.va=function(){this.u.unsubscribe("onlineScreenChange",(0,g.D)(this.hI,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.D);var a=AUa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.Vb(b||[],a);g.he(this.i);g.Q.prototype.va.call(this)};
g.k.ke=function(a){T7("Controller",a)};
g.k.LM=function(a,b){this.i==a&&(b||x8(this,null),this.ea("yt-remote-cast2-session-change",b))};
g.k.hV=function(a,b){if(!this.isDisposed())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),v8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)v8("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{v8("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.ea("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:x8(this,
new t8(this.u,a));break;case chrome.cast.ReceiverType.DIAL:x8(this,new p8(this.u,a,this.C,this.config_));break;case chrome.cast.ReceiverType.CAST:x8(this,new m8(this.u,a,this.config_));break;default:this.ke("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.ke("Stopping receiver w/o session: "+a.friendlyName)}else this.ke("onReceiverAction_ called without receiver.")};
g.k.fU=function(a){if(this.isDisposed())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.ke("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.ke("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return v8("Reselecting dial screen."),
this.ea("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.ke('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);x8(this,new p8(this.u,b,this.C,this.config_))}b=this.i;b.S=a;b.S.appState==chrome.cast.DialAppState.RUNNING?(a=b.S.extraData||{},c=a.screenId||null,q8(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=eVa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.S.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.et(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=fVa(b,c)):a=fVa(b,c)):a=s8(b);return a};
g.k.JM=function(a){var b=this;if(!this.isDisposed()&&!this.I){v8("New cast session ID: "+a.sessionId);var c=a.receiver;if(c.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(c.receiverType==chrome.cast.ReceiverType.CAST)v8("Got resumed cast session before resumed mdx connection."),c.friendlyName=chrome.cast.unescape(c.friendlyName),x8(this,new m8(this.u,c,this.config_),!0);else{this.ke("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var d=this.i.i,e=$6(this.u.Gh(),
d.label);e&&V6(e,c.label)&&d.receiverType!=chrome.cast.ReceiverType.CAST&&c.receiverType==chrome.cast.ReceiverType.CAST&&(v8("onSessionEstablished_: manual to cast session change "+c.friendlyName),g.he(this.i),this.i=new m8(this.u,c,this.config_),this.i.subscribe("sessionScreen",(0,g.D)(this.LM,this,this.i)),this.i.subscribe("sessionFailed",function(){return jVa(b,b.i)}),this.i.Ps(null));
this.i.jG(a)}}};
g.k.tQ=function(){return this.i?this.i.gI():null};
g.k.EV=function(a){this.isDisposed()||(this.ke("Failed to estabilish a session: "+g.li(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&x8(this,null),this.ea("yt-remote-cast2-session-failed"))};
g.k.kV=function(a){v8("Receiver availability updated: "+a);if(!this.isDisposed()){var b=w8(this);this.K=a==chrome.cast.ReceiverAvailability.AVAILABLE;w8(this)!=b&&this.ea("yt-remote-cast2-availability-change",w8(this))}};
g.k.hI=function(){this.isDisposed()||(this.B=kVa(this),v8("Updating custom receivers: "+g.li(this.B)),chrome.cast.setCustomReceivers(this.B,g.Ia,(0,g.D)(function(){this.ke("Failed to set custom receivers.")},this)),this.ea("yt-remote-cast2-availability-change",w8(this)))};
u8.prototype.setLaunchParams=u8.prototype.XW;u8.prototype.setConnectedScreenStatus=u8.prototype.WW;u8.prototype.stopSession=u8.prototype.uQ;u8.prototype.getCastSession=u8.prototype.tQ;u8.prototype.requestSession=u8.prototype.requestSession;u8.prototype.init=u8.prototype.init;u8.prototype.dispose=u8.prototype.dispose;var D8=[];g.k=I8.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";J8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Ik=a.hasPrevious,this.hasNext=a.hasNext,this.K=a.playerTime,this.I=a.playerTimeAt,this.C=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.S=a.loadedTime,this.B=a.liveIngestionTime,this.u=
!isNaN(this.B))};
g.k.Dc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.Kj=function(a){this.D=isNaN(a)?0:a};
g.k.getDuration=function(){return this.u?this.D+K8(this):this.D};
g.k.clone=function(){return new I8(O8(this))};g.v(Q8,g.Q);g.k=Q8.prototype;g.k.getState=function(){return this.B};
g.k.play=function(){S8(this)?(this.i?this.i.play(null,g.Ia,X8(this,"play")):W8(this,"play"),V8(this,1,M8(R8(this))),this.ea("remotePlayerChange")):T8(this,this.play)};
g.k.pause=function(){S8(this)?(this.i?this.i.pause(null,g.Ia,X8(this,"pause")):W8(this,"pause"),V8(this,2,M8(R8(this))),this.ea("remotePlayerChange")):T8(this,this.pause)};
g.k.seekTo=function(a){if(S8(this)){if(this.i){var b=R8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Dc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,X8(this,"seekTo",{newTime:a}))}else W8(this,"seekTo",{newTime:a});V8(this,3,a);this.ea("remotePlayerChange")}else T8(this,g.Sa(this.seekTo,a))};
g.k.stop=function(){if(S8(this)){this.i?this.i.stop(null,g.Ia,X8(this,"stopVideo")):W8(this,"stopVideo");var a=R8(this);a.index=-1;a.videoId="";J8(a);U8(this,a);this.ea("remotePlayerChange")}else T8(this,this.stop)};
g.k.setVolume=function(a,b){if(S8(this)){var c=R8(this);if(this.u){if(c.volume!=a){var d=Math.round(a)/100;this.u.setReceiverVolumeLevel(d,(0,g.D)(function(){T7("CP","set receiver volume: "+d)},this),(0,g.D)(function(){this.ke("failed to set receiver volume.")},this))}c.muted!=b&&this.u.setReceiverMuted(b,(0,g.D)(function(){T7("CP","set receiver muted: "+b)},this),(0,g.D)(function(){this.ke("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);W8(this,"setVolume",e)}c.muted=b;c.volume=a;U8(this,c)}else T8(this,g.Sa(this.setVolume,a,b))};
g.k.iI=function(a,b){if(S8(this)){var c=R8(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.li(b.style),g.Oe(a,c.trackData));W8(this,"setSubtitlesTrack",a);U8(this,c)}else T8(this,g.Sa(this.iI,a,b))};
g.k.setAudioTrack=function(a,b){S8(this)?(b=b.getLanguageInfo().getId(),W8(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=R8(this),a.audioTrackId=b,U8(this,a)):T8(this,g.Sa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){d=void 0===d?null:d;e=void 0===e?null:e;f=void 0===f?null:f;h=void 0===h?null:h;var l=R8(this),m={videoId:a};void 0!==c&&(m.currentIndex=c);N8(l,a,c||0);void 0!==b&&(L8(l,b),m.currentTime=b);d&&(m.listId=d);e&&(m.playerParams=e);f&&(m.clickTrackingParams=f);h&&(m.locationInfo=g.li(h));W8(this,"setPlaylist",m);d||U8(this,l)};
g.k.GA=function(a,b){if(S8(this)){if(a&&b){var c=R8(this);N8(c,a,b);U8(this,c)}W8(this,"previous")}else T8(this,g.Sa(this.GA,a,b))};
g.k.nextVideo=function(a,b){if(S8(this)){if(a&&b){var c=R8(this);N8(c,a,b);U8(this,c)}W8(this,"next")}else T8(this,g.Sa(this.nextVideo,a,b))};
g.k.Pr=function(){if(S8(this)){W8(this,"clearPlaylist");var a=R8(this);a.reset();U8(this,a);this.ea("remotePlayerChange")}else T8(this,this.Pr)};
g.k.RJ=function(){S8(this)?W8(this,"dismissAutoplay"):T8(this,this.RJ)};
g.k.dispose=function(){if(3!=this.B){var a=this.B;this.B=3;this.ea("proxyStateChange",a,this.B)}g.Q.prototype.dispose.call(this)};
g.k.va=function(){wVa(this);this.C=null;this.D.clear();P8(this,null);g.Q.prototype.va.call(this)};
g.k.lG=function(a){if((a!=this.B||2==a)&&3!=this.B&&0!=a){var b=this.B;this.B=a;this.ea("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,0===b.i.length&&(b.i=b.u,b.i.reverse(),b.u=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.fV=function(a,b){this.ea(a,b)};
g.k.OT=function(a){if(!a)this.Aw(null),P8(this,null);else if(this.u.receiver.volume){a=this.u.receiver.volume;var b=R8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)T7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,U8(this,b)}};
g.k.Aw=function(a){T7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.S);if(this.i=a)this.i.addUpdateListener(this.S),xVa(this),this.ea("remotePlayerChange")};
g.k.NT=function(a){a?(xVa(this),this.ea("remotePlayerChange")):this.Aw(null)};
g.k.GG=function(){W8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.VT=function(){var a=tVa();a&&P8(this,a)};
g.k.ke=function(a){T7("CP",a)};g.v(Y8,g.Q);g.k=Y8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.videoIds,f=b.playerParams,h=b.clickTrackingParams,l=b.index,m={videoId:d},n=b.currentTime,p=b.locationInfo;b=b.loopMode;void 0!==n&&(m.currentTime=5>=n?0:n);f&&(m.playerParams=f);p&&(m.locationInfo=p);h&&(m.clickTrackingParams=h);c&&(m.listId=c);e&&0<e.length&&(m.videoIds=e.join(","));void 0!==l&&(m.currentIndex=l);this.Ba&&(m.loopMode=b||"LOOP_MODE_OFF");c&&(this.jc.listId=c);this.jc.videoId=d;this.jc.index=l||0;this.jc.state=3;L8(this.jc,
n);this.C="UNSUPPORTED";c=this.Ba?"setInitialState":"setPlaylist";Z8("Connecting with "+c+" and params: "+g.li(m));this.i.connect({method:c,params:g.li(m)},a,GTa())}else Z8("Connecting without params"),this.i.connect({},a,GTa());AVa(this)};
g.k.ZA=function(a){this.i.ZA(a)};
g.k.dispose=function(){this.isDisposed()||(g.Ga("yt.mdx.remote.remoteClient_",null,void 0),this.ea("beforeDispose"),$8(this,3));g.Q.prototype.dispose.call(this)};
g.k.va=function(){a9(this);c9(this);b9(this);g.Yt(this.K);this.K=NaN;g.Yt(this.S);this.S=NaN;this.B=null;g.cv(this.X);this.X.length=0;this.i.dispose();g.Q.prototype.va.call(this);this.C=this.I=this.u=this.jc=this.i=null};
g.k.VR=function(){this.Zr(2)};
g.k.ST=function(){Z8("Channel opened");this.xa&&(this.xa=!1,b9(this),this.oa=g.Wt((0,g.D)(function(){Z8("Timing out waiting for a screen.");this.Zr(1)},this),15E3));
KTa(yUa(this.i),this.Ka)};
g.k.PT=function(){Z8("Channel closed");isNaN(this.D)?e7(!0):e7();this.dispose()};
g.k.QT=function(a,b){e7();isNaN(this.Nv())?(b&&"shortLived"==this.Aa&&this.ea("browserChannelAuthError",a),Z8("Channel error: "+a+" without reconnection"),this.dispose()):(this.xa=!0,Z8("Channel error: "+a+" with reconnection in "+this.Nv()+" ms"),$8(this,2))};
g.k.dL=function(a){if(!this.u||0===this.u.length)return!1;for(var b=g.r(this.u),c=b.next();!c.done;c=b.next())if(!c.value.capabilities.has(a))return!1;return!0};
g.k.RT=function(a){a.params?Z8("Received: action="+a.action+", params="+g.li(a.params)):Z8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=R6(a.params.devices);this.u=g.Qm(a,function(c){return new T6(c)});
a=!!g.Nb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
DVa(this,a);a=this.dL("mlm");this.ea("multiStateLoopEnabled",a);break;case "loungeScreenDisconnected":g.Wb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
DVa(this,!1);break;case "remoteConnected":var b=new T6(R6(a.params.device));g.Nb(this.u,function(c){return b?c.id==b.id:!1})||tTa(this.u,b);
break;case "remoteDisconnected":b=new T6(R6(a.params.device));g.Wb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":FVa(this,a);break;case "nowPlaying":HVa(this,a);break;case "onStateChange":GVa(this,a);break;case "onAdStateChange":IVa(this,a);break;case "onVolumeChanged":JVa(this,a);break;case "onSubtitlesTrackChanged":EVa(this,a);break;case "nowAutoplaying":KVa(this,a);break;case "autoplayDismissed":this.ea("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.ea("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.ea("autoplayModeChange",this.C);"DISABLED"==this.C&&this.ea("autoplayDismissed");break;case "onHasPreviousNextChanged":LVa(this,a);break;case "requestAssistedSignIn":this.ea("assistedSignInRequested",a.params.authCode);break;case "onLoopModeChanged":this.ea("loopModeChange",a.params.loopMode);break;default:Z8("Unrecognized action: "+a.action)}};
g.k.KW=function(){if(this.B){var a=this.B;this.B=null;this.jc.videoId!=a&&d9(this,"getNowPlaying")}};
g.k.SR=function(){var a=3;this.isDisposed()||(a=0,isNaN(this.Nv())?O7(this.i)&&isNaN(this.D)&&(a=1):a=2);return a};
g.k.Zr=function(a){Z8("Disconnecting with "+a);g.Ga("yt.mdx.remote.remoteClient_",null,void 0);a9(this);this.ea("beforeDisconnect",a);1==a&&e7();zUa(this.i,a);this.dispose()};
g.k.QR=function(){var a=this.jc;this.B&&(a=this.jc.clone(),N8(a,this.B,a.index));return O8(a)};
g.k.YW=function(a){var b=new I8(a);b.videoId&&b.videoId!=this.jc.videoId&&(this.B=b.videoId,g.Yt(this.K),this.K=g.Wt((0,g.D)(this.KW,this),5E3));var c=[];this.jc.listId==b.listId&&this.jc.videoId==b.videoId&&this.jc.index==b.index||c.push("remoteQueueChange");this.jc.playerState==b.playerState&&this.jc.volume==b.volume&&this.jc.muted==b.muted&&M8(this.jc)==M8(b)&&g.li(this.jc.trackData)==g.li(b.trackData)||c.push("remotePlayerChange");this.jc.reset(a);g.lc(c,function(d){this.ea(d)},this)};
g.k.uK=function(){var a=this.i.I.id,b=g.Nb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Nv=function(){var a=this.i;return a.u.isActive()?a.u.u-Date.now():NaN};
g.k.NR=function(){return this.C||"UNSUPPORTED"};
g.k.OR=function(){return this.I||""};
g.k.vQ=function(){if(!isNaN(this.Nv())){var a=this.i.u;g.gr(a.i);a.start()}};
g.k.VW=function(a,b){d9(this,a,b);CVa(this)};
g.k.jI=function(){var a=g.pu("SID","")||"",b=g.pu("SAPISID","")||"",c=g.pu("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.zc(g.eb(a),2);b=g.zc(g.eb(b),2);c=g.zc(g.eb(c),2);return g.zc(g.eb(a+","+b+","+c),2)};
Y8.prototype.subscribe=Y8.prototype.subscribe;Y8.prototype.unsubscribeByKey=Y8.prototype.ag;Y8.prototype.getProxyState=Y8.prototype.SR;Y8.prototype.disconnect=Y8.prototype.Zr;Y8.prototype.getPlayerContextData=Y8.prototype.QR;Y8.prototype.setPlayerContextData=Y8.prototype.YW;Y8.prototype.getOtherConnectedRemoteId=Y8.prototype.uK;Y8.prototype.getReconnectTimeout=Y8.prototype.Nv;Y8.prototype.getAutoplayMode=Y8.prototype.NR;Y8.prototype.getAutoplayVideoId=Y8.prototype.OR;Y8.prototype.reconnect=Y8.prototype.vQ;
Y8.prototype.sendMessage=Y8.prototype.VW;Y8.prototype.getXsrfToken=Y8.prototype.jI;Y8.prototype.isCapabilitySupportedOnConnectedDevices=Y8.prototype.dL;g.v(e9,X7);g.k=e9.prototype;g.k.Gh=function(a){return this.Re.$_gs(a)};
g.k.contains=function(a){return!!this.Re.$_c(a)};
g.k.get=function(a){return this.Re.$_g(a)};
g.k.start=function(){this.Re.$_st()};
g.k.add=function(a,b,c){this.Re.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Re.$_r(a,b,c)};
g.k.tB=function(a,b,c,d){this.Re.$_un(a,b,c,d)};
g.k.va=function(){for(var a=0,b=this.i.length;a<b;++a)this.Re.$_ubk(this.i[a]);this.i.length=0;this.Re=null;X7.prototype.va.call(this)};
g.k.wQ=function(){this.ea("screenChange")};
g.k.MU=function(){this.ea("onlineScreenChange")};
g8.prototype.$_st=g8.prototype.start;g8.prototype.$_gspc=g8.prototype.qQ;g8.prototype.$_gsppc=g8.prototype.fI;g8.prototype.$_c=g8.prototype.contains;g8.prototype.$_g=g8.prototype.get;g8.prototype.$_a=g8.prototype.add;g8.prototype.$_un=g8.prototype.tB;g8.prototype.$_r=g8.prototype.remove;g8.prototype.$_gs=g8.prototype.Gh;g8.prototype.$_gos=g8.prototype.eI;g8.prototype.$_s=g8.prototype.subscribe;g8.prototype.$_ubk=g8.prototype.ag;var r9=null,x9=!1,f9=null,g9=null,w9=null,k9=[];g.v(y9,g.E);g.k=y9.prototype;g.k.va=function(){g.E.prototype.va.call(this);this.i.stop();this.B.stop();this.S.stop();this.oa();var a=this.Tb;a.unsubscribe("proxyStateChange",this.HM,this);a.unsubscribe("remotePlayerChange",this.Fw,this);a.unsubscribe("remoteQueueChange",this.sA,this);a.unsubscribe("previousNextChange",this.EM,this);a.unsubscribe("nowAutoplaying",this.yM,this);a.unsubscribe("autoplayDismissed",this.bM,this);this.Tb=this.u=null};
g.k.sj=function(a){var b=g.Ba.apply(1,arguments);if(2!=this.Tb.B)if(z9(this)){var c=a;if(!R8(this.Tb).isAdPlaying()||"control_seek"!==c)switch(c){case "control_toggle_play_pause":R8(this.Tb).Dc()?this.Tb.pause():this.Tb.play();break;case "control_play":this.Tb.play();break;case "control_pause":this.Tb.pause();break;case "control_seek":this.K.dI(b[0],b[1]);break;case "control_subtitles_set_track":A9(this,b[0]);break;case "control_set_audio_track":this.setAudioTrack(b[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":b=
this.J.getCurrentTime();B9(this,0===b?void 0:b);break;case "control_seek":B9(this,b[0]);break;case "control_subtitles_set_track":A9(this,b[0]);break;case "control_set_audio_track":this.setAudioTrack(b[0])}};
g.k.KT=function(a){this.S.kQ(a)};
g.k.DX=function(a){this.sj("control_subtitles_set_track",g.He(a)?null:a)};
g.k.XN=function(){var a=this.J.getOption("captions","track");g.He(a)||A9(this,a)};
g.k.Xb=function(a){this.u.Xb(a,this.J.getVideoData().lengthSeconds)};
g.k.xU=function(){g.He(this.C)||WVa(this,this.C);this.D=!1};
g.k.HM=function(a,b){this.B.stop();2===b&&this.RN()};
g.k.Fw=function(){if(z9(this)){this.i.stop();var a=R8(this.Tb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.vf=1;break;case 1082:case 1083:this.u.vf=0;break;default:this.u.vf=-1}switch(a.playerState){case 1081:case 1:this.Ub(new g.GJ(8));this.QN();break;case 1085:case 3:this.Ub(new g.GJ(9));break;case 1083:case 0:this.Ub(new g.GJ(2));this.K.stop();this.Xb(this.J.getVideoData().lengthSeconds);break;case 1084:this.Ub(new g.GJ(4));break;case 2:this.Ub(new g.GJ(4));this.Xb(M8(a));
break;case -1:this.Ub(new g.GJ(64));break;case -1E3:this.Ub(new g.GJ(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=R8(this.Tb).trackData;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,WVa(this,a));a=R8(this.Tb);-1===a.volume||Math.round(this.J.getVolume())===a.volume&&this.J.isMuted()===a.muted||this.X.isActive()||this.zO()}else VVa(this)};
g.k.EM=function(){this.J.ea("mdxpreviousnextchange")};
g.k.sA=function(){z9(this)||VVa(this)};
g.k.yM=function(a){isNaN(a)||this.J.ea("mdxnowautoplaying",a)};
g.k.bM=function(){this.J.ea("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){z9(this)&&this.Tb.setAudioTrack(this.J.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===R8(this.Tb).playerState?B9(this,a):b&&this.Tb.seekTo(a)};
g.k.zO=function(){var a=this;if(z9(this)){var b=R8(this.Tb);this.events.lc(this.Z);b.muted?this.J.mute():this.J.unMute();this.J.setVolume(b.volume);this.Z=this.events.T(this.J,"onVolumeChange",function(c){UVa(a,c)})}};
g.k.QN=function(){this.i.stop();if(!this.Tb.isDisposed()){var a=R8(this.Tb);a.Dc()&&this.Ub(new g.GJ(8));this.Xb(M8(a));this.i.start()}};
g.k.RN=function(){this.B.stop();this.i.stop();var a=this.Tb.C.getReconnectTimeout();2==this.Tb.B&&!isNaN(a)&&this.B.start()};
g.k.Ub=function(a){this.B.stop();var b=this.I;if(!g.LJ(b,a)){var c=g.T(a,2);c!==g.T(this.I,2)&&this.J.Ct(c);this.I=a;YVa(this.u,b,a)}};g.v(C9,g.W);C9.prototype.yd=function(){this.i.show()};
C9.prototype.Fb=function(){this.i.hide()};
C9.prototype.u=function(){S6("mdx-privacy-popup-cancel");this.Fb()};
C9.prototype.B=function(){S6("mdx-privacy-popup-confirm");this.Fb()};g.v(D9,g.W);D9.prototype.onStateChange=function(a){XVa(this,a.state)};g.v(E9,g.FP);E9.prototype.D=function(){var a=this.J.getOption("remote","receivers");a&&1<a.length&&!this.J.getOption("remote","quickCast")?(this.Bo=g.oc(a,this.i,this),g.GP(this,g.Qm(a,this.i)),a=this.J.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.Xh(a),this.enable(!0)):this.enable(!1)};
E9.prototype.i=function(a){return a.key};
E9.prototype.lj=function(a){return"cast-selector-receiver"===a?"Cast...":this.Bo[a].name};
E9.prototype.Af=function(a){g.FP.prototype.Af.call(this,a);this.J.setOption("remote","currentReceiver",this.Bo[a]);this.Ab.Fb()};g.v(F9,g.PM);g.k=F9.prototype;
g.k.create=function(){var a=this.player.V(),b=g.JE(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:a.N("mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:a.N("enable_dial_short_lived_lounge_token"),enableCastLoungeToken:a.N("enable_cast_short_lived_lounge_token")};PVa(b,a);this.subscriptions.push(g.Jv("yt-remote-before-disconnect",this.JT,this));this.subscriptions.push(g.Jv("yt-remote-connection-change",this.lV,this));this.subscriptions.push(g.Jv("yt-remote-receiver-availability-change",this.GM,
this));this.subscriptions.push(g.Jv("yt-remote-auto-connect",this.jV,this));this.subscriptions.push(g.Jv("yt-remote-receiver-resumed",this.iV,this));this.subscriptions.push(g.Jv("mdx-privacy-popup-confirm",this.xW,this));this.subscriptions.push(g.Jv("mdx-privacy-popup-cancel",this.wW,this));this.GM()};
g.k.load=function(){this.player.cancelPlayback();g.PM.prototype.load.call(this);this.di=new y9(this,this.player,this.Tb);var a=(a=TVa())?a.currentTime:0;var b=v9()?new Q8(p9(),void 0):null;0==a&&b&&(a=M8(R8(b)));0!==a&&this.Xb(a);YVa(this,this.zd,this.zd);this.player.Wk(6)};
g.k.unload=function(){this.player.ea("mdxautoplaycanceled");this.cn=this.Pk;(0,g.ie)(this.di,this.Tb);this.Tb=this.di=null;g.PM.prototype.unload.call(this);this.player.Wk(5);G9(this)};
g.k.va=function(){g.Kv(this.subscriptions);g.PM.prototype.va.call(this)};
g.k.Rk=function(a){var b=g.Ba.apply(1,arguments);this.loaded&&this.di.sj.apply(this.di,[a].concat(g.la(b)))};
g.k.getAdState=function(){return this.vf};
g.k.Ik=function(){return this.Tb?R8(this.Tb).Ik:!1};
g.k.hasNext=function(){return this.Tb?R8(this.Tb).hasNext:!1};
g.k.Xb=function(a,b){this.tL=a||0;this.player.ea("progresssync",a,b);this.player.Ma("onVideoProgress",a||0)};
g.k.getCurrentTime=function(){return this.tL};
g.k.getProgressState=function(){var a=R8(this.Tb),b=this.player.getVideoData();return{airingStart:0,airingEnd:0,allowSeeking:this.player.V().N("web_player_mdx_allow_seeking_change_killswitch")?this.player.sf():!a.isAdPlaying()&&this.player.sf(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.B+K8(a):a.B,isAtLiveHead:1>=(a.u?a.i+K8(a):a.i)-this.getCurrentTime(),loaded:a.S,seekableEnd:a.u?a.i+K8(a):a.i,seekableStart:0<
a.C?a.C+K8(a):a.C}};
g.k.nextVideo=function(){this.Tb&&this.Tb.nextVideo()};
g.k.GA=function(){this.Tb&&this.Tb.GA()};
g.k.JT=function(a){1===a&&(this.KF=this.Tb?R8(this.Tb):null)};
g.k.lV=function(){var a=v9()?new Q8(p9(),void 0):null;if(a){var b=this.cn;this.loaded&&this.unload();this.Tb=a;this.KF=null;b.key!==this.Pk.key&&(this.cn=b,this.load())}else(0,g.he)(this.Tb),this.Tb=null,this.loaded&&(this.unload(),(a=this.KF)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,M8(a)));this.player.ea("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.GM=function(){var a=[this.Pk],b=a.concat,c=QVa();E8()&&g.Gy("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Bo=b.call(a,c);a=q9()||this.Pk;H9(this,a);this.player.Ma("onMdxReceiversChange")};
g.k.jV=function(){var a=q9();H9(this,a)};
g.k.iV=function(){this.cn=q9()};
g.k.xW=function(){this.Ow=!0;G9(this);x9=!1;r9&&t9(r9,1);r9=null};
g.k.wW=function(){this.Ow=!1;G9(this);H9(this,this.Pk);this.cn=this.Pk;x9=!1;r9=null;this.player.playVideo()};
g.k.jf=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Bo;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?G8():H9(this,b)),this.loaded?this.cn:this.Pk;case "quickCast":return 2===this.Bo.length&&"cast-selector-receiver"===this.Bo[1].key?(b&&G8(),!0):!1}};
g.k.GG=function(){this.Tb.GG()};
g.k.Qi=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.OM("remote",F9);})(_yt_player);
